// 样式定义
const styles = {
  // App容器
  app: {
    minHeight: '100vh',
    backgroundColor: '#f0f4ff',
    fontFamily: "'Microsoft YaHei', 'Segoe UI', sans-serif",
  },
  
  // 导航栏
  navbar: {
    background: 'linear-gradient(135deg, #1a237e 0%, #0d47a1 100%)',
    color: 'white',
    padding: '1rem 2rem',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    position: 'sticky',
    top: 0,
    zIndex: 100,
    boxShadow: '0 2px 10px rgba(0,0,0,0.1)',
  },
  logo: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  logoIcon: {
    fontSize: '2rem',
    color: '#ff6b35',
  },
  logoText: {
    fontSize: '1.4rem',
    fontWeight: 600,
  },
  navItems: {
    display: 'flex',
    gap: '0.5rem',
    flex: 1,
    justifyContent: 'center',
  },
  navItem: {
    padding: '0.6rem 1rem',
    background: 'rgba(255,255,255,0.1)',
    border: 'none',
    color: 'white',
    borderRadius: '8px',
    cursor: 'pointer',
    fontSize: '0.9rem',
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    transition: 'all 0.3s',
  },
  navItemActive: {
    padding: '0.6rem 1rem',
    background: '#ff6b35',
    border: 'none',
    color: 'white',
    borderRadius: '8px',
    cursor: 'pointer',
    fontSize: '0.9rem',
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
  },
  userArea: {
    display: 'flex',
    alignItems: 'center',
    gap: '1rem',
  },
  logoutBtn: {
    padding: '0.5rem 1rem',
    background: 'rgba(255,255,255,0.2)',
    border: 'none',
    color: 'white',
    borderRadius: '20px',
    cursor: 'pointer',
  },
  
  // 页面容器
  page: {
    minHeight: 'calc(100vh - 70px)',
  },
  
  // 英雄区
  hero: {
    background: 'linear-gradient(135deg, #0a0a2e 0%, #1a1a5e 50%, #0d1b2a 100%)',
    color: 'white',
    padding: '4rem 2rem',
    textAlign: 'center',
    position: 'relative',
    overflow: 'hidden',
    minHeight: '450px',
  },
  particles: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
    zIndex: 1,
  },
  heroContent: {
    position: 'relative',
    zIndex: 2,
  },
  heroTitle: {
    fontSize: '2.8rem',
    marginBottom: '1rem',
  },
  heroSubtitle: {
    fontSize: '1.3rem',
    maxWidth: '800px',
    margin: '0 auto 2rem',
    opacity: 0.9,
  },
  statsRow: {
    display: 'flex',
    justifyContent: 'center',
    gap: '4rem',
    margin: '2rem 0',
    flexWrap: 'wrap',
  },
  statBox: {
    textAlign: 'center',
  },
  statNumber: {
    fontSize: '3rem',
    fontWeight: 700,
    background: 'linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
  },
  statLabel: {
    fontSize: '1.1rem',
    marginTop: '0.5rem',
  },
  statSub: {
    fontSize: '0.9rem',
    opacity: 0.7,
  },
  
  // 模块区域
  moduleSection: {
    padding: '2rem',
    background: 'linear-gradient(180deg, #f0f4ff 0%, #f8f9fa 100%)',
  },
  moduleGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(250px, 1fr))',
    gap: '1.5rem',
    maxWidth: '1200px',
    margin: '0 auto',
  },
  moduleCard: {
    background: 'white',
    padding: '2rem',
    borderRadius: '16px',
    textAlign: 'center',
    cursor: 'pointer',
    transition: 'all 0.3s',
    boxShadow: '0 4px 20px rgba(0,0,0,0.08)',
  },
  moduleIcon: {
    width: '70px',
    height: '70px',
    background: 'linear-gradient(135deg, #1a73e8 0%, #0d47a1 100%)',
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    margin: '0 auto 1rem',
    fontSize: '1.8rem',
    color: 'white',
  },
  moduleTitle: {
    fontSize: '1.2rem',
    fontWeight: 600,
    marginBottom: '0.5rem',
  },
  moduleDesc: {
    color: '#666',
    fontSize: '0.9rem',
  },
  
  // 页面标题
  pageHeader: {
    padding: '2rem',
    textAlign: 'center',
    background: 'white',
    marginBottom: '1rem',
  },
  pageTitle: {
    fontSize: '1.8rem',
    color: '#1a237e',
    marginBottom: '0.5rem',
  },
  pageSubtitle: {
    color: '#666',
    fontSize: '1rem',
  },
  
  // 筛选栏
  filterBar: {
    padding: '1rem 2rem',
    background: 'white',
    display: 'flex',
    gap: '1rem',
    alignItems: 'center',
    flexWrap: 'wrap',
    boxShadow: '0 2px 10px rgba(0,0,0,0.05)',
  },
  searchInput: {
    padding: '0.6rem 1rem',
    border: '1px solid #ddd',
    borderRadius: '20px',
    width: '250px',
    fontSize: '0.9rem',
  },
  categoryTabs: {
    display: 'flex',
    gap: '0.5rem',
    flexWrap: 'wrap',
  },
  categoryTab: {
    padding: '0.5rem 1rem',
    background: '#f0f4ff',
    border: 'none',
    color: '#1a73e8',
    borderRadius: '20px',
    cursor: 'pointer',
    fontSize: '0.85rem',
  },
  categoryTabActive: {
    padding: '0.5rem 1rem',
    background: 'linear-gradient(135deg, #1a73e8 0%, #0d47a1 100%)',
    border: 'none',
    color: 'white',
    borderRadius: '20px',
    cursor: 'pointer',
    fontSize: '0.85rem',
  },
  
  // 技能网格
  skillsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(350px, 1fr))',
    gap: '1.5rem',
    padding: '2rem',
    maxWidth: '1400px',
    margin: '0 auto',
  },
  skillCard: {
    background: 'white',
    borderRadius: '16px',
    overflow: 'hidden',
    boxShadow: '0 4px 20px rgba(0,0,0,0.08)',
    transition: 'all 0.3s',
  },
  skillHeader: {
    padding: '1.5rem',
    background: 'linear-gradient(135deg, #1a73e8 0%, #0d47a1 100%)',
    color: 'white',
    display: 'flex',
    alignItems: 'center',
    gap: '1rem',
  },
  skillIcon: {
    width: '50px',
    height: '50px',
    background: 'rgba(255,255,255,0.2)',
    borderRadius: '12px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '1.5rem',
  },
  skillBody: {
    padding: '1.5rem',
  },
  skillDesc: {
    color: '#555',
    marginBottom: '1rem',
    fontSize: '0.9rem',
  },
  skillTags: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '0.5rem',
    marginBottom: '1rem',
  },
  tag: {
    background: '#e3f2fd',
    color: '#1a73e8',
    padding: '0.3rem 0.8rem',
    borderRadius: '12px',
    fontSize: '0.8rem',
  },
  skillMeta: {
    display: 'flex',
    justifyContent: 'space-between',
    marginBottom: '1rem',
    color: '#666',
    fontSize: '0.85rem',
  },
  skillActions: {
    display: 'flex',
    gap: '0.8rem',
  },
  downloadBtn: {
    flex: 2,
    background: 'linear-gradient(135deg, #ff6b35 0%, #e55a2b 100%)',
    color: 'white',
    border: 'none',
    padding: '0.8rem',
    borderRadius: '8px',
    cursor: 'pointer',
    fontWeight: 600,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.5rem',
  },
  detailBtn: {
    flex: 1,
    background: 'white',
    color: '#1a73e8',
    border: '2px solid #1a73e8',
    padding: '0.8rem',
    borderRadius: '8px',
    cursor: 'pointer',
    fontWeight: 600,
  },
  
  // 案例网格
  casesGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(320px, 1fr))',
    gap: '1.5rem',
    padding: '2rem',
    maxWidth: '1400px',
    margin: '0 auto',
  },
  caseCard: {
    background: 'white',
    borderRadius: '16px',
    overflow: 'hidden',
    boxShadow: '0 4px 20px rgba(0,0,0,0.08)',
  },
  caseImage: {
    height: '150px',
    background: 'linear-gradient(135deg, #1a73e8 0%, #0d47a1 100%)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: 'white',
    fontSize: '3rem',
  },
  caseBody: {
    padding: '1.5rem',
  },
  caseDept: {
    display: 'inline-block',
    background: '#e3f2fd',
    color: '#1a73e8',
    padding: '0.3rem 0.8rem',
    borderRadius: '12px',
    fontSize: '0.8rem',
    marginBottom: '0.5rem',
  },
  caseTitle: {
    fontSize: '1.2rem',
    marginBottom: '0.5rem',
  },
  caseDesc: {
    color: '#666',
    fontSize: '0.9rem',
    marginBottom: '1rem',
  },
  caseStats: {
    display: 'flex',
    justifyContent: 'space-around',
    paddingTop: '1rem',
    borderTop: '1px solid #f0f0f0',
  },
  caseStatItem: {
    textAlign: 'center',
  },
  caseStatNum: {
    fontSize: '1.2rem',
    fontWeight: 600,
    color: '#1a73e8',
  },
  caseStatLabel: {
    fontSize: '0.75rem',
    color: '#999',
  },
  
  // 数据看板
  statsOverview: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
    gap: '1.5rem',
    padding: '2rem',
    maxWidth: '1400px',
    margin: '0 auto',
  },
  overviewCard: {
    background: 'white',
    padding: '1.5rem',
    borderRadius: '16px',
    textAlign: 'center',
    boxShadow: '0 4px 20px rgba(0,0,0,0.08)',
  },
  overviewIcon: {
    width: '60px',
    height: '60px',
    background: 'linear-gradient(135deg, #1a73e8 0%, #0d47a1 100%)',
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    margin: '0 auto 1rem',
    color: 'white',
    fontSize: '1.5rem',
  },
  overviewNum: {
    fontSize: '2rem',
    fontWeight: 700,
    color: '#1a237e',
  },
  overviewLabel: {
    color: '#666',
    marginTop: '0.5rem',
  },
  deptGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))',
    gap: '1.5rem',
    padding: '2rem',
    maxWidth: '1400px',
    margin: '0 auto',
  },
  deptCard: {
    background: 'white',
    padding: '1.5rem',
    borderRadius: '16px',
    boxShadow: '0 4px 20px rgba(0,0,0,0.08)',
  },
  deptHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '1rem',
    marginBottom: '1rem',
  },
  deptIcon: {
    width: '45px',
    height: '45px',
    background: '#e3f2fd',
    borderRadius: '12px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#1a73e8',
    fontSize: '1.2rem',
  },
  deptName: {
    fontSize: '1.1rem',
    fontWeight: 600,
  },
  deptProgress: {
    marginBottom: '1rem',
  },
  progressBar: {
    height: '10px',
    background: '#e8eaf6',
    borderRadius: '5px',
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    background: 'linear-gradient(90deg, #1a73e8, #ff6b35)',
    borderRadius: '5px',
  },
  progressLabel: {
    display: 'flex',
    justifyContent: 'space-between',
    marginTop: '0.5rem',
    fontSize: '0.85rem',
    color: '#666',
  },
  deptStats: {
    display: 'flex',
    justifyContent: 'space-around',
  },
  deptStatItem: {
    textAlign: 'center',
  },
  deptStatNum: {
    fontSize: '1.3rem',
    fontWeight: 600,
    color: '#1a73e8',
  },
  deptStatLabel: {
    fontSize: '0.75rem',
    color: '#999',
  },
  
  // 帮助中心
  helpGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))',
    gap: '1.5rem',
    padding: '2rem',
    maxWidth: '1200px',
    margin: '0 auto',
  },
  helpCard: {
    background: 'linear-gradient(135deg, #f0f4ff 0%, #e3f2fd 100%)',
    padding: '2rem',
    borderRadius: '16px',
    textAlign: 'center',
    cursor: 'pointer',
    transition: 'all 0.3s',
  },
  helpIcon: {
    width: '70px',
    height: '70px',
    background: 'white',
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    margin: '0 auto 1rem',
    color: '#1a73e8',
    fontSize: '1.8rem',
  },
  helpTitle: {
    fontSize: '1.2rem',
    fontWeight: 600,
    marginBottom: '0.5rem',
  },
  helpDesc: {
    color: '#666',
    fontSize: '0.9rem',
  },
  installSection: {
    background: 'linear-gradient(135deg, #1a237e 0%, #0d47a1 100%)',
    color: 'white',
    padding: '3rem 2rem',
    textAlign: 'center',
    marginTop: '2rem',
  },
  installTitle: {
    fontSize: '1.8rem',
    marginBottom: '0.5rem',
  },
  installDesc: {
    opacity: 0.9,
    marginBottom: '2rem',
  },
  
  // 个人中心
  profileCard: {
    background: 'white',
    padding: '2rem',
    borderRadius: '16px',
    display: 'flex',
    alignItems: 'center',
    gap: '1.5rem',
    maxWidth: '800px',
    margin: '0 auto 2rem',
    boxShadow: '0 4px 20px rgba(0,0,0,0.08)',
  },
  profileAvatar: {
    width: '80px',
    height: '80px',
    background: 'linear-gradient(135deg, #1a73e8 0%, #0d47a1 100%)',
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: 'white',
    fontSize: '2rem',
    fontWeight: 600,
  },
  profileInfo: {},
  tokenSection: {
    background: 'white',
    padding: '2rem',
    borderRadius: '16px',
    maxWidth: '800px',
    margin: '0 auto',
    boxShadow: '0 4px 20px rgba(0,0,0,0.08)',
  },
  sectionTitle: {
    fontSize: '1.3rem',
    marginBottom: '1.5rem',
    color: '#1a237e',
  },
  tokenCards: {
    display: 'flex',
    flexDirection: 'column',
    gap: '1rem',
    marginBottom: '1.5rem',
  },
  tokenCard: {
    padding: '1rem',
    background: '#f8f9fa',
    borderRadius: '12px',
  },
  tokenLabel: {
    fontWeight: 600,
    marginBottom: '0.5rem',
  },
  tokenProgress: {
    marginBottom: '0.5rem',
  },
  tokenInfo: {
    display: 'flex',
    justifyContent: 'space-between',
    fontSize: '0.85rem',
    color: '#666',
  },
  applyBtn: {
    width: '100%',
    padding: '0.8rem',
    background: 'linear-gradient(135deg, #1a73e8 0%, #0d47a1 100%)',
    color: 'white',
    border: 'none',
    borderRadius: '8px',
    cursor: 'pointer',
    fontWeight: 600,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.5rem',
  },
  
  // 管理员后台
  adminTabs: {
    display: 'flex',
    gap: '0.5rem',
    padding: '1rem 2rem',
    background: 'white',
    borderBottom: '1px solid #e0e0e0',
  },
  adminTab: {
    padding: '0.7rem 1.2rem',
    background: 'none',
    border: 'none',
    color: '#666',
    borderBottom: '2px solid transparent',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
  },
  adminTabActive: {
    padding: '0.7rem 1.2rem',
    background: 'none',
    border: 'none',
    color: '#1a73e8',
    borderBottom: '2px solid #1a73e8',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
  },
  badge: {
    background: '#ff6b35',
    color: 'white',
    padding: '0.2rem 0.5rem',
    borderRadius: '10px',
    fontSize: '0.7rem',
  },
  adminContent: {
    padding: '2rem',
  },
  adminTitle: {
    fontSize: '1.3rem',
    marginBottom: '1rem',
    color: '#1a237e',
  },
  table: {
    width: '100%',
    background: 'white',
    borderRadius: '12px',
    overflow: 'hidden',
    boxShadow: '0 4px 20px rgba(0,0,0,0.08)',
  },
  approveBtn: {
    padding: '0.4rem 0.8rem',
    background: '#28a745',
    color: 'white',
    border: 'none',
    borderRadius: '5px',
    cursor: 'pointer',
    marginRight: '0.5rem',
  },
  rejectBtn: {
    padding: '0.4rem 0.8rem',
    background: '#dc3545',
    color: 'white',
    border: 'none',
    borderRadius: '5px',
    cursor: 'pointer',
    marginRight: '0.5rem',
  },
  viewBtn: {
    padding: '0.4rem 0.8rem',
    background: '#1a73e8',
    color: 'white',
    border: 'none',
    borderRadius: '5px',
    cursor: 'pointer',
  },
  actionBtn: {
    padding: '0.4rem 0.8rem',
    background: '#e3f2fd',
    color: '#1a73e8',
    border: 'none',
    borderRadius: '5px',
    cursor: 'pointer',
    marginRight: '0.5rem',
  },
  offlineBtn: {
    padding: '0.4rem 0.8rem',
    background: '#ffc107',
    color: '#333',
    border: 'none',
    borderRadius: '5px',
    cursor: 'pointer',
  },
  roleTag: {
    padding: '0.3rem 0.6rem',
    background: '#e3f2fd',
    color: '#1a73e8',
    borderRadius: '12px',
    fontSize: '0.8rem',
  },
  statusPublished: {
    padding: '0.3rem 0.6rem',
    background: '#d4edda',
    color: '#155724',
    borderRadius: '12px',
    fontSize: '0.8rem',
  },
  statusPending: {
    padding: '0.3rem 0.6rem',
    background: '#fff3cd',
    color: '#856404',
    borderRadius: '12px',
    fontSize: '0.8rem',
  },
  tokenForm: {
    background: 'white',
    padding: '2rem',
    borderRadius: '12px',
    display: 'flex',
    gap: '1rem',
    flexWrap: 'wrap',
    boxShadow: '0 4px 20px rgba(0,0,0,0.08)',
  },
  formInput: {
    padding: '0.6rem 1rem',
    border: '1px solid #ddd',
    borderRadius: '8px',
    fontSize: '0.9rem',
  },
  formSelect: {
    padding: '0.6rem 1rem',
    border: '1px solid #ddd',
    borderRadius: '8px',
    fontSize: '0.9rem',
  },
  submitBtn: {
    padding: '0.6rem 1.5rem',
    background: 'linear-gradient(135deg, #1a73e8 0%, #0d47a1 100%)',
    color: 'white',
    border: 'none',
    borderRadius: '8px',
    cursor: 'pointer',
    fontWeight: 600,
  },
  
  // 登录页
  loginPage: {
    minHeight: '100vh',
    background: 'linear-gradient(135deg, #0a0a2e 0%, #1a1a5e 50%, #0d1b2a 100%)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '2rem',
  },
  loginCard: {
    background: 'white',
    padding: '3rem',
    borderRadius: '20px',
    maxWidth: '400px',
    width: '100%',
    textAlign: 'center',
    boxShadow: '0 20px 60px rgba(0,0,0,0.3)',
  },
  loginLogo: {
    fontSize: '4rem',
    color: '#ff6b35',
    marginBottom: '1rem',
  },
  loginTitle: {
    fontSize: '1.8rem',
    color: '#1a237e',
    marginBottom: '0.5rem',
  },
  loginSubtitle: {
    color: '#666',
    marginBottom: '2rem',
  },
  loginForm: {
    display: 'flex',
    flexDirection: 'column',
    gap: '1rem',
  },
  loginInput: {
    padding: '0.8rem 1rem',
    border: '1px solid #ddd',
    borderRadius: '10px',
    fontSize: '1rem',
  },
  loginBtn: {
    padding: '0.8rem',
    background: 'linear-gradient(135deg, #ff6b35 0%, #e55a2b 100%)',
    color: 'white',
    border: 'none',
    borderRadius: '10px',
    cursor: 'pointer',
    fontSize: '1rem',
    fontWeight: 600,
    marginTop: '1rem',
  },
  loginTips: {
    marginTop: '2rem',
    padding: '1rem',
    background: '#f8f9fa',
    borderRadius: '10px',
    fontSize: '0.85rem',
    color: '#666',
    textAlign: 'left',
  },
  
  // 技能详情页
  backBtn: {
    padding: '0.6rem 1.2rem',
    background: 'white',
    border: '1px solid #ddd',
    borderRadius: '8px',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    marginBottom: '1.5rem',
    fontSize: '0.9rem',
    color: '#666',
  },
  detailHeader: {
    background: 'white',
    padding: '2rem',
    borderRadius: '16px',
    display: 'flex',
    alignItems: 'flex-start',
    gap: '1.5rem',
    marginBottom: '1.5rem',
    boxShadow: '0 4px 20px rgba(0,0,0,0.08)',
  },
  detailIcon: {
    width: '80px',
    height: '80px',
    background: 'linear-gradient(135deg, #1a73e8 0%, #0d47a1 100%)',
    borderRadius: '16px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: 'white',
    fontSize: '2rem',
    flexShrink: 0,
  },
  detailInfo: {
    flex: 1,
  },
  detailTitle: {
    fontSize: '1.8rem',
    color: '#1a237e',
    marginBottom: '0.3rem',
  },
  detailSubtitle: {
    color: '#666',
    fontSize: '0.95rem',
    marginBottom: '1rem',
  },
  detailMeta: {
    display: 'flex',
    gap: '1rem',
    marginBottom: '1rem',
    flexWrap: 'wrap',
  },
  detailTag: {
    color: '#666',
    fontSize: '0.85rem',
    display: 'flex',
    alignItems: 'center',
    gap: '0.3rem',
  },
  detailTags: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '0.5rem',
  },
  detailActions: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.8rem',
  },
  secondaryBtn: {
    padding: '0.8rem 1.5rem',
    background: '#f0f4ff',
    color: '#1a73e8',
    border: 'none',
    borderRadius: '8px',
    cursor: 'pointer',
    fontWeight: 600,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.5rem',
  },
  detailContent: {
    display: 'grid',
    gridTemplateColumns: '1fr 320px',
    gap: '1.5rem',
    padding: '0 2rem 2rem',
    maxWidth: '1400px',
    margin: '0 auto',
  },
  detailMain: {
    display: 'flex',
    flexDirection: 'column',
    gap: '1.5rem',
  },
  detailSection: {
    background: 'white',
    padding: '1.5rem',
    borderRadius: '16px',
    boxShadow: '0 4px 20px rgba(0,0,0,0.08)',
  },
  sectionTitle: {
    fontSize: '1.2rem',
    color: '#1a237e',
    marginBottom: '1rem',
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
  },
  detailDesc: {
    color: '#555',
    lineHeight: 1.8,
    fontSize: '0.95rem',
  },
  featuresList: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
    gap: '0.8rem',
  },
  featureItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    color: '#555',
    padding: '0.5rem',
    background: '#f8f9fa',
    borderRadius: '8px',
  },
  useSteps: {
    display: 'flex',
    flexDirection: 'column',
    gap: '1rem',
  },
  useStep: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: '1rem',
  },
  stepNumber: {
    width: '28px',
    height: '28px',
    background: 'linear-gradient(135deg, #1a73e8 0%, #0d47a1 100%)',
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: 'white',
    fontSize: '0.85rem',
    fontWeight: 600,
    flexShrink: 0,
  },
  stepText: {
    color: '#555',
    lineHeight: 1.6,
    paddingTop: '0.2rem',
  },
  
  // 评论
  commentForm: {
    marginBottom: '1.5rem',
    paddingBottom: '1.5rem',
    borderBottom: '1px solid #f0f0f0',
  },
  ratingSelect: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    marginBottom: '1rem',
  },
  starBtn: {
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    fontSize: '1.2rem',
    color: '#ddd',
    padding: '0.2rem',
  },
  starActive: {
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    fontSize: '1.2rem',
    color: '#ffc107',
    padding: '0.2rem',
  },
  commentInput: {
    width: '100%',
    padding: '0.8rem',
    border: '1px solid #ddd',
    borderRadius: '8px',
    fontSize: '0.95rem',
    resize: 'vertical',
    fontFamily: 'inherit',
    marginBottom: '1rem',
  },
  commentsList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '1rem',
  },
  commentCard: {
    display: 'flex',
    gap: '1rem',
    padding: '1rem',
    background: '#f8f9fa',
    borderRadius: '12px',
  },
  commentAvatar: {
    width: '40px',
    height: '40px',
    background: 'linear-gradient(135deg, #1a73e8 0%, #0d47a1 100%)',
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: 'white',
    fontWeight: 600,
    flexShrink: 0,
  },
  commentContent: {
    flex: 1,
  },
  commentHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.8rem',
    marginBottom: '0.5rem',
  },
  commentUser: {
    fontWeight: 600,
    color: '#1a237e',
  },
  commentRating: {
    display: 'flex',
    gap: '0.1rem',
  },
  starFilled: {
    color: '#ffc107',
    fontSize: '0.8rem',
  },
  starEmpty: {
    color: '#ddd',
    fontSize: '0.8rem',
  },
  commentText: {
    color: '#555',
    fontSize: '0.9rem',
    lineHeight: 1.5,
    marginBottom: '0.5rem',
  },
  commentDate: {
    fontSize: '0.8rem',
    color: '#999',
  },
  noComments: {
    textAlign: 'center',
    color: '#999',
    padding: '2rem',
  },
  
  // 侧边栏
  detailSidebar: {
    display: 'flex',
    flexDirection: 'column',
    gap: '1rem',
  },
  sidebarCard: {
    background: 'white',
    padding: '1.5rem',
    borderRadius: '16px',
    boxShadow: '0 4px 20px rgba(0,0,0,0.08)',
  },
  sidebarTitle: {
    fontSize: '1.1rem',
    color: '#1a237e',
    marginBottom: '1rem',
    paddingBottom: '0.8rem',
    borderBottom: '1px solid #f0f0f0',
  },
  infoList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.8rem',
  },
  infoItem: {
    display: 'flex',
    justifyContent: 'space-between',
  },
  infoLabel: {
    color: '#666',
    fontSize: '0.9rem',
  },
  infoValue: {
    color: '#1a237e',
    fontWeight: 600,
    fontSize: '0.9rem',
  },
  hotSkills: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.8rem',
  },
  hotSkillItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.8rem',
    padding: '0.6rem',
    background: '#f8f9fa',
    borderRadius: '8px',
    color: '#555',
    cursor: 'pointer',
    transition: 'all 0.2s',
  },
  
  // 投稿按钮
  submitCaseBtnContainer: {
    padding: '0 2rem 1rem',
    textAlign: 'right',
    maxWidth: '1400px',
    margin: '0 auto',
  },
  submitCaseBtn: {
    padding: '0.8rem 1.5rem',
    background: 'linear-gradient(135deg, #ff6b35 0%, #e55a2b 100%)',
    color: 'white',
    border: 'none',
    borderRadius: '8px',
    cursor: 'pointer',
    fontWeight: 600,
    display: 'inline-flex',
    alignItems: 'center',
    gap: '0.5rem',
    fontSize: '0.95rem',
  },
  
  // 投稿表单
  submitFormCard: {
    background: 'white',
    padding: '2rem',
    borderRadius: '16px',
    maxWidth: '800px',
    margin: '0 auto 2rem',
    boxShadow: '0 4px 20px rgba(0,0,0,0.08)',
  },
  submitFormTitle: {
    fontSize: '1.5rem',
    color: '#1a237e',
    marginBottom: '0.5rem',
    textAlign: 'center',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.5rem',
  },
  submitFormSubtitle: {
    color: '#666',
    textAlign: 'center',
    marginBottom: '2rem',
  },
  submitForm: {
    display: 'flex',
    flexDirection: 'column',
    gap: '1.2rem',
  },
  formGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.5rem',
  },
  formRow: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '1rem',
  },
  formLabel: {
    fontWeight: 600,
    color: '#333',
    fontSize: '0.95rem',
  },
  required: {
    color: '#dc3545',
  },
  formInput: {
    padding: '0.8rem 1rem',
    border: '1px solid #ddd',
    borderRadius: '8px',
    fontSize: '0.95rem',
    fontFamily: 'inherit',
  },
  formSelect: {
    padding: '0.8rem 1rem',
    border: '1px solid #ddd',
    borderRadius: '8px',
    fontSize: '0.95rem',
    fontFamily: 'inherit',
    background: 'white',
  },
  formTextarea: {
    padding: '0.8rem 1rem',
    border: '1px solid #ddd',
    borderRadius: '8px',
    fontSize: '0.95rem',
    fontFamily: 'inherit',
    resize: 'vertical',
  },
  uploadArea: {
    position: 'relative',
  },
  fileInput: {
    position: 'absolute',
    width: '0',
    height: '0',
    opacity: 0,
  },
  uploadLabel: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '2rem',
    border: '2px dashed #ddd',
    borderRadius: '12px',
    cursor: 'pointer',
    color: '#666',
    transition: 'all 0.3s',
    gap: '0.5rem',
  },
  previewGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(120px, 1fr))',
    gap: '1rem',
    marginTop: '1rem',
  },
  previewItem: {
    position: 'relative',
    borderRadius: '8px',
    overflow: 'hidden',
  },
  previewImage: {
    width: '100%',
    height: '100px',
    objectFit: 'cover',
    borderRadius: '8px',
  },
  removeImageBtn: {
    position: 'absolute',
    top: '5px',
    right: '5px',
    width: '24px',
    height: '24px',
    background: 'rgba(0,0,0,0.6)',
    color: 'white',
    border: 'none',
    borderRadius: '50%',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '0.8rem',
  },
  formActions: {
    display: 'flex',
    gap: '1rem',
    marginTop: '1rem',
  },
  cancelBtn: {
    flex: 1,
    padding: '0.8rem',
    background: '#f0f0f0',
    color: '#666',
    border: 'none',
    borderRadius: '8px',
    cursor: 'pointer',
    fontWeight: 600,
  },
  
  // 成功页面
  successCard: {
    background: 'white',
    padding: '4rem 2rem',
    borderRadius: '16px',
    textAlign: 'center',
    maxWidth: '500px',
    margin: '2rem auto',
    boxShadow: '0 4px 20px rgba(0,0,0,0.08)',
  },
  successIcon: {
    fontSize: '5rem',
    color: '#28a745',
    marginBottom: '1.5rem',
  },
  successTitle: {
    fontSize: '1.8rem',
    color: '#1a237e',
    marginBottom: '1rem',
  },
  successText: {
    color: '#666',
    marginBottom: '2rem',
    lineHeight: 1.6,
  },
  
  // 提示框
  noticeBox: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.8rem',
    padding: '1rem',
    background: '#fff3cd',
    borderRadius: '8px',
    marginBottom: '1.5rem',
    color: '#856404',
  },
  
  // 用户技能列表
  userSkillsList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '1rem',
  },
  userSkillItem: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '1rem',
    background: '#f8f9fa',
    borderRadius: '12px',
  },
  userSkillInfo: {
    display: 'flex',
    alignItems: 'center',
    gap: '1rem',
  },
  userSkillIcon: {
    width: '40px',
    height: '40px',
    background: 'linear-gradient(135deg, #1a73e8 0%, #0d47a1 100%)',
    borderRadius: '10px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: 'white',
  },
  userSkillName: {
    fontWeight: 600,
    color: '#1a237e',
    marginBottom: '0.3rem',
  },
  userSkillMeta: {
    display: 'flex',
    gap: '1rem',
    fontSize: '0.85rem',
  },
  downloadCount: {
    color: '#666',
  },
  userSkillActions: {
    display: 'flex',
    gap: '0.5rem',
  },
  
  // 周期选择
  chartPeriodSelect: {
    display: 'flex',
    gap: '0.5rem',
    marginBottom: '1.5rem',
  },
  periodBtn: {
    padding: '0.5rem 1rem',
    background: '#f0f4ff',
    border: 'none',
    color: '#1a73e8',
    borderRadius: '20px',
    cursor: 'pointer',
    fontSize: '0.85rem',
  },
  periodBtnActive: {
    padding: '0.5rem 1rem',
    background: 'linear-gradient(135deg, #1a73e8 0%, #0d47a1 100%)',
    border: 'none',
    color: 'white',
    borderRadius: '20px',
    cursor: 'pointer',
    fontSize: '0.85rem',
  },
  
  // 图表
  chartContainer: {
    background: '#f8f9fa',
    borderRadius: '12px',
    padding: '1.5rem',
    marginBottom: '1rem',
  },
  chart: {
    display: 'flex',
    alignItems: 'flex-end',
    justifyContent: 'space-around',
    height: '200px',
    gap: '0.5rem',
  },
  chartBar: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    height: '100%',
    justifyContent: 'flex-end',
  },
  barFill: {
    width: '80%',
    background: 'linear-gradient(180deg, #1a73e8 0%, #0d47a1 100%)',
    borderRadius: '4px 4px 0 0',
    minHeight: '10px',
    transition: 'height 0.3s',
  },
  barLabel: {
    fontSize: '0.7rem',
    color: '#666',
    marginTop: '0.5rem',
    textAlign: 'center',
  },
  
  // 累计任务
  totalTasks: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '1rem',
    background: 'linear-gradient(135deg, #1a237e 0%, #0d47a1 100%)',
    borderRadius: '12px',
    color: 'white',
  },
  totalTasksNum: {
    fontSize: '1.5rem',
    fontWeight: 700,
  },
  
  // 排行榜
  leaderboardSection: {
    padding: '2rem',
    maxWidth: '1400px',
    margin: '0 auto',
  },
  leaderboardHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '1.5rem',
  },
  leaderboardTitle: {
    fontSize: '1.5rem',
    color: '#1a237e',
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
  },
  periodTabs: {
    display: 'flex',
    gap: '0.5rem',
  },
  periodTab: {
    padding: '0.5rem 1rem',
    background: '#f0f4ff',
    border: 'none',
    color: '#1a73e8',
    borderRadius: '20px',
    cursor: 'pointer',
    fontSize: '0.85rem',
  },
  periodTabActive: {
    padding: '0.5rem 1rem',
    background: 'linear-gradient(135deg, #1a73e8 0%, #0d47a1 100%)',
    border: 'none',
    color: 'white',
    borderRadius: '20px',
    cursor: 'pointer',
    fontSize: '0.85rem',
  },
  leaderboardGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(320px, 1fr))',
    gap: '1.5rem',
  },
  leaderboardCard: {
    background: 'white',
    borderRadius: '16px',
    padding: '1.5rem',
    boxShadow: '0 4px 20px rgba(0,0,0,0.08)',
  },
  leaderboardCardTitle: {
    fontSize: '1.1rem',
    color: '#1a237e',
    marginBottom: '1rem',
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
  },
  leaderboardList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.8rem',
  },
  leaderboardItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.8rem',
    padding: '0.8rem',
    background: '#f8f9fa',
    borderRadius: '10px',
  },
  rankBadge: {
    width: '28px',
    height: '28px',
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#333',
    fontWeight: 700,
    fontSize: '0.85rem',
    flexShrink: 0,
  },
  avatar: {
    width: '36px',
    height: '36px',
    background: 'linear-gradient(135deg, #1a73e8 0%, #0d47a1 100%)',
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: 'white',
    fontWeight: 600,
    fontSize: '0.9rem',
    flexShrink: 0,
  },
  leaderboardInfo: {
    flex: 1,
  },
  leaderboardFullInfo: {
    flex: 1,
  },
  leaderboardName: {
    fontWeight: 600,
    color: '#333',
    fontSize: '0.95rem',
  },
  leaderboardDept: {
    fontSize: '0.8rem',
    color: '#666',
  },
  leaderboardValue: {
    fontWeight: 700,
    color: '#1a73e8',
    fontSize: '1.1rem',
  },
  
  // 投稿按钮
  submitSkillBtn: {
    background: 'linear-gradient(135deg, #ff6b35 0%, #f7931e 100%)',
    color: 'white',
    border: 'none',
    padding: '0.6rem 1.2rem',
    borderRadius: '20px',
    cursor: 'pointer',
    fontSize: '0.95rem',
    fontWeight: 600,
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    transition: 'transform 0.2s',
  },
  
  // 提示框
  noticeBox: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.8rem',
    padding: '1rem',
    background: '#fff3cd',
    borderRadius: '8px',
    marginBottom: '1.5rem',
    color: '#856404',
  },
  
  // 投稿表单
  submitFormCard: {
    background: 'white',
    borderRadius: '16px',
    padding: '2rem',
    maxWidth: '800px',
    margin: '0 auto',
    boxShadow: '0 4px 20px rgba(0,0,0,0.08)',
  },
  submitFormTitle: {
    fontSize: '1.8rem',
    color: '#1a237e',
    marginBottom: '0.5rem',
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
  },
  submitFormSubtitle: {
    color: '#666',
    marginBottom: '1.5rem',
  },
  submitForm: {
    display: 'flex',
    flexDirection: 'column',
    gap: '1.2rem',
  },
  formRow: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '1rem',
  },
  formGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.5rem',
  },
  formLabel: {
    fontWeight: 600,
    color: '#333',
    fontSize: '0.95rem',
  },
  required: {
    color: '#e74c3c',
  },
  formInput: {
    padding: '0.8rem 1rem',
    border: '1px solid #ddd',
    borderRadius: '8px',
    fontSize: '1rem',
    outline: 'none',
    transition: 'border-color 0.2s',
  },
  formSelect: {
    padding: '0.8rem 1rem',
    border: '1px solid #ddd',
    borderRadius: '8px',
    fontSize: '1rem',
    outline: 'none',
    background: 'white',
  },
  formTextarea: {
    padding: '0.8rem 1rem',
    border: '1px solid #ddd',
    borderRadius: '8px',
    fontSize: '1rem',
    outline: 'none',
    resize: 'vertical',
    fontFamily: 'inherit',
  },
  formActions: {
    display: 'flex',
    justifyContent: 'flex-end',
    gap: '1rem',
    marginTop: '1rem',
  },
  cancelBtn: {
    padding: '0.8rem 1.5rem',
    background: '#f0f0f0',
    border: 'none',
    borderRadius: '8px',
    cursor: 'pointer',
    fontSize: '1rem',
    color: '#666',
  },
  submitBtn: {
    padding: '0.8rem 1.5rem',
    background: 'linear-gradient(135deg, #1a73e8 0%, #0d47a1 100%)',
    border: 'none',
    borderRadius: '8px',
    cursor: 'pointer',
    fontSize: '1rem',
    color: 'white',
    fontWeight: 600,
  },
  
  // 用户技能列表
  userSkillsList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '1rem',
  },
  userSkillItem: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '1rem',
    background: '#f8f9fa',
    borderRadius: '12px',
  },
  userSkillInfo: {
    display: 'flex',
    alignItems: 'center',
    gap: '1rem',
  },
  userSkillIcon: {
    width: '40px',
    height: '40px',
    background: 'linear-gradient(135deg, #1a73e8 0%, #0d47a1 100%)',
    borderRadius: '10px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: 'white',
  },
  userSkillName: {
    fontWeight: 600,
    color: '#1a237e',
    marginBottom: '0.3rem',
  },
  userSkillMeta: {
    display: 'flex',
    gap: '1rem',
    fontSize: '0.85rem',
    alignItems: 'center',
  },
  downloadCount: {
    color: '#666',
  },
  userSkillActions: {
    display: 'flex',
    gap: '0.5rem',
  },
  
  // 状态标签
  statusPublished: {
    color: '#28a745',
    fontWeight: 600,
  },
  statusPending: {
    color: '#ffc107',
    fontWeight: 600,
  },
  excellentBadge: {
    background: 'linear-gradient(135deg, #ffd700 0%, #ffb700 100%)',
    color: '#333',
    padding: '0.2rem 0.5rem',
    borderRadius: '4px',
    fontSize: '0.75rem',
    fontWeight: 700,
    display: 'flex',
    alignItems: 'center',
    gap: '0.2rem',
  },
  submissionDate: {
    color: '#999',
    fontSize: '0.8rem',
  },
  
  // 周期选择
  chartPeriodSelect: {
    display: 'flex',
    gap: '0.5rem',
    marginBottom: '1.5rem',
  },
  periodBtn: {
    padding: '0.5rem 1rem',
    background: '#f0f4ff',
    border: 'none',
    color: '#1a73e8',
    borderRadius: '20px',
    cursor: 'pointer',
    fontSize: '0.85rem',
  },
  periodBtnActive: {
    padding: '0.5rem 1rem',
    background: 'linear-gradient(135deg, #1a73e8 0%, #0d47a1 100%)',
    border: 'none',
    color: 'white',
    borderRadius: '20px',
    cursor: 'pointer',
    fontSize: '0.85rem',
  },
  
  // 图表
  chartContainer: {
    background: '#f8f9fa',
    borderRadius: '12px',
    padding: '1.5rem',
    marginBottom: '1rem',
  },
  chart: {
    display: 'flex',
    alignItems: 'flex-end',
    justifyContent: 'space-around',
    height: '200px',
    gap: '0.5rem',
  },
  chartBar: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    height: '100%',
    justifyContent: 'flex-end',
  },
  barFill: {
    width: '80%',
    background: 'linear-gradient(180deg, #1a73e8 0%, #0d47a1 100%)',
    borderRadius: '4px 4px 0 0',
    minHeight: '10px',
    transition: 'height 0.3s',
  },
  barLabel: {
    fontSize: '0.7rem',
    color: '#666',
    marginTop: '0.5rem',
    textAlign: 'center',
  },
  
  // 累计任务
  totalTasks: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '1rem',
    background: 'linear-gradient(135deg, #1a237e 0%, #0d47a1 100%)',
    borderRadius: '12px',
    color: 'white',
  },
  totalTasksNum: {
    fontSize: '1.5rem',
    fontWeight: 700,
  },
  
  // 排行榜
  leaderboardSection: {
    padding: '2rem',
    maxWidth: '1400px',
    margin: '0 auto',
  },
  leaderboardHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '1.5rem',
  },
  leaderboardTitle: {
    fontSize: '1.5rem',
    color: '#1a237e',
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
  },
  periodTabs: {
    display: 'flex',
    gap: '0.5rem',
  },
  periodTab: {
    padding: '0.5rem 1rem',
    background: '#f0f4ff',
    border: 'none',
    color: '#1a73e8',
    borderRadius: '20px',
    cursor: 'pointer',
    fontSize: '0.85rem',
  },
  periodTabActive: {
    padding: '0.5rem 1rem',
    background: 'linear-gradient(135deg, #1a73e8 0%, #0d47a1 100%)',
    border: 'none',
    color: 'white',
    borderRadius: '20px',
    cursor: 'pointer',
    fontSize: '0.85rem',
  },
  leaderboardGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(320px, 1fr))',
    gap: '1.5rem',
  },
  leaderboardCard: {
    background: 'white',
    borderRadius: '16px',
    padding: '1.5rem',
    boxShadow: '0 4px 20px rgba(0,0,0,0.08)',
  },
  leaderboardCardTitle: {
    fontSize: '1.1rem',
    color: '#1a237e',
    marginBottom: '1rem',
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
  },
  leaderboardList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.8rem',
  },
  leaderboardItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.8rem',
    padding: '0.8rem',
    background: '#f8f9fa',
    borderRadius: '10px',
  },
  
  // 查看按钮
  viewBtn: {
    padding: '0.4rem 0.8rem',
    background: '#1a73e8',
    border: 'none',
    borderRadius: '6px',
    color: 'white',
    cursor: 'pointer',
    fontSize: '0.85rem',
  },
  
  // 成功页面
  successCard: {
    background: 'white',
    padding: '4rem 2rem',
    borderRadius: '16px',
    textAlign: 'center',
    maxWidth: '500px',
    margin: '2rem auto',
    boxShadow: '0 4px 20px rgba(0,0,0,0.08)',
  },
  successIcon: {
    fontSize: '5rem',
    color: '#28a745',
    marginBottom: '1.5rem',
  },
  successTitle: {
    fontSize: '1.8rem',
    color: '#1a237e',
    marginBottom: '1rem',
  },
  successText: {
    color: '#666',
    marginBottom: '2rem',
    lineHeight: 1.6,
  },
  
  // 返回按钮
  backBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '0.5rem',
    padding: '0.6rem 1rem',
    background: '#f0f0f0',
    border: 'none',
    borderRadius: '8px',
    cursor: 'pointer',
    color: '#333',
    fontSize: '0.95rem',
    marginBottom: '1.5rem',
  },
};

export default styles;
