// 样式定义
const styles = {
  // App容器
  app: {
    minHeight: '100vh',
    backgroundColor: '#f0f4ff',
    fontFamily: "'Microsoft YaHei', 'Segoe UI', sans-serif",
  },
  
  // 导航栏
  navbar: {
    background: 'linear-gradient(135deg, #1a237e 0%, #0d47a1 100%)',
    color: 'white',
    padding: '1rem 2rem',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    position: 'sticky',
    top: 0,
    zIndex: 100,
    boxShadow: '0 2px 10px rgba(0,0,0,0.1)',
  },
  logo: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  logoIcon: {
    fontSize: '2rem',
    color: '#ff6b35',
  },
  logoText: {
    fontSize: '1.4rem',
    fontWeight: 600,
  },
  navItems: {
    display: 'flex',
    gap: '0.5rem',
    flex: 1,
    justifyContent: 'center',
  },
  navItem: {
    padding: '0.6rem 1rem',
    background: 'rgba(255,255,255,0.1)',
    border: 'none',
    color: 'white',
    borderRadius: '8px',
    cursor: 'pointer',
    fontSize: '0.9rem',
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    transition: 'all 0.3s',
  },
  navItemActive: {
    padding: '0.6rem 1rem',
    background: '#ff6b35',
    border: 'none',
    color: 'white',
    borderRadius: '8px',
    cursor: 'pointer',
    fontSize: '0.9rem',
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
  },
  userArea: {
    display: 'flex',
    alignItems: 'center',
    gap: '1rem',
  },
  notificationBtn: {
    position: 'relative',
    padding: '0.5rem 0.8rem',
    background: 'rgba(255,255,255,0.2)',
    border: 'none',
    color: 'white',
    borderRadius: '50%',
    cursor: 'pointer',
    fontSize: '1.1rem',
    width: '40px',
    height: '40px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    transition: 'all 0.3s',
  },
  notificationBadge: {
    position: 'absolute',
    top: '-5px',
    right: '-5px',
    background: '#ff6b6b',
    color: 'white',
    borderRadius: '50%',
    width: '20px',
    height: '20px',
    fontSize: '0.7rem',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontWeight: 600,
  },
  logoutBtn: {
    padding: '0.5rem 1rem',
    background: 'rgba(255,255,255,0.2)',
    border: 'none',
    color: 'white',
    borderRadius: '20px',
    cursor: 'pointer',
  },
  
  // 页面容器
  page: {
    minHeight: 'calc(100vh - 70px)',
  },
  
  // 英雄区
  hero: {
    background: 'linear-gradient(135deg, #0a0a2e 0%, #1a1a5e 50%, #0d1b2a 100%)',
    color: 'white',
    padding: '4rem 2rem',
    textAlign: 'center',
    position: 'relative',
    overflow: 'hidden',
    minHeight: '450px',
  },
  particles: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
    zIndex: 1,
  },
  heroContent: {
    position: 'relative',
    zIndex: 2,
  },
  heroTitle: {
    fontSize: '2.8rem',
    marginBottom: '1rem',
  },
  heroSubtitle: {
    fontSize: '1.3rem',
    maxWidth: '800px',
    margin: '0 auto 2rem',
    opacity: 0.9,
  },
  statsRow: {
    display: 'flex',
    justifyContent: 'center',
    gap: '4rem',
    margin: '2rem 0',
    flexWrap: 'wrap',
  },
  statBox: {
    textAlign: 'center',
  },
  statNumber: {
    fontSize: '3rem',
    fontWeight: 700,
    background: 'linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
  },
  statLabel: {
    fontSize: '1.1rem',
    marginTop: '0.5rem',
  },
  statSub: {
    fontSize: '0.9rem',
    opacity: 0.7,
  },
  
  // 模块区域
  moduleSection: {
    padding: '2rem',
    background: 'linear-gradient(180deg, #f0f4ff 0%, #f8f9fa 100%)',
  },
  moduleGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(250px, 1fr))',
    gap: '1.5rem',
    maxWidth: '1200px',
    margin: '0 auto',
  },
  moduleCard: {
    background: 'white',
    padding: '2rem',
    borderRadius: '16px',
    textAlign: 'center',
    cursor: 'pointer',
    transition: 'all 0.3s',
    boxShadow: '0 4px 20px rgba(0,0,0,0.08)',
  },
  moduleIcon: {
    width: '70px',
    height: '70px',
    background: 'linear-gradient(135deg, #1a73e8 0%, #0d47a1 100%)',
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    margin: '0 auto 1rem',
    fontSize: '1.8rem',
    color: 'white',
  },
  moduleTitle: {
    fontSize: '1.2rem',
    fontWeight: 600,
    marginBottom: '0.5rem',
  },
  moduleDesc: {
    color: '#666',
    fontSize: '0.9rem',
  },
  
  // 页面标题
  pageHeader: {
    padding: '2rem',
    textAlign: 'center',
    background: 'white',
    marginBottom: '1rem',
  },
  pageTitle: {
    fontSize: '1.8rem',
    color: '#1a237e',
    marginBottom: '0.5rem',
  },
  pageSubtitle: {
    color: '#666',
    fontSize: '1rem',
  },
  
  // 筛选栏
  filterBar: {
    padding: '1rem 2rem',
    background: 'white',
    display: 'flex',
    gap: '1rem',
    alignItems: 'center',
    flexWrap: 'wrap',
    boxShadow: '0 2px 10px rgba(0,0,0,0.05)',
  },
  searchInput: {
    padding: '0.6rem 1rem',
    border: '1px solid #ddd',
    borderRadius: '20px',
    width: '250px',
    fontSize: '0.9rem',
  },
  categoryTabs: {
    display: 'flex',
    gap: '0.5rem',
    flexWrap: 'wrap',
  },
  categoryTab: {
    padding: '0.5rem 1rem',
    background: '#f0f4ff',
    border: 'none',
    color: '#1a73e8',
    borderRadius: '20px',
    cursor: 'pointer',
    fontSize: '0.85rem',
  },
  categoryTabActive: {
    padding: '0.5rem 1rem',
    background: 'linear-gradient(135deg, #1a73e8 0%, #0d47a1 100%)',
    border: 'none',
    color: 'white',
    borderRadius: '20px',
    cursor: 'pointer',
    fontSize: '0.85rem',
  },
  
  // 技能网格
  skillsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(350px, 1fr))',
    gap: '1.5rem',
    padding: '2rem',
    maxWidth: '1400px',
    margin: '0 auto',
  },
  skillCard: {
    background: 'white',
    borderRadius: '16px',
    overflow: 'hidden',
    boxShadow: '0 4px 20px rgba(0,0,0,0.08)',
    transition: 'all 0.3s',
  },
  skillHeader: {
    padding: '1.5rem',
    background: 'linear-gradient(135deg, #1a73e8 0%, #0d47a1 100%)',
    color: 'white',
    display: 'flex',
    alignItems: 'center',
    gap: '1rem',
  },
  skillIcon: {
    width: '50px',
    height: '50px',
    background: 'rgba(255,255,255,0.2)',
    borderRadius: '12px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '1.5rem',
  },
  skillBody: {
    padding: '1.5rem',
  },
  skillDesc: {
    color: '#555',
    marginBottom: '1rem',
    fontSize: '0.9rem',
  },
  skillTags: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '0.5rem',
    marginBottom: '1rem',
  },
  tag: {
    background: '#e3f2fd',
    color: '#1a73e8',
    padding: '0.3rem 0.8rem',
    borderRadius: '12px',
    fontSize: '0.8rem',
  },
  skillMeta: {
    display: 'flex',
    justifyContent: 'space-between',
    marginBottom: '1rem',
    color: '#666',
    fontSize: '0.85rem',
  },
  skillActions: {
    display: 'flex',
    gap: '0.8rem',
  },
  downloadBtn: {
    flex: 2,
    background: 'linear-gradient(135deg, #ff6b35 0%, #e55a2b 100%)',
    color: 'white',
    border: 'none',
    padding: '0.8rem',
    borderRadius: '8px',
    cursor: 'pointer',
    fontWeight: 600,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.5rem',
  },
  detailBtn: {
    flex: 1,
    background: 'white',
    color: '#1a73e8',
    border: '2px solid #1a73e8',
    padding: '0.8rem',
    borderRadius: '8px',
    cursor: 'pointer',
    fontWeight: 600,
  },
  
  // 技能需求区域
  requestsSection: {
    marginTop: '2rem',
    padding: '1.5rem',
    background: 'linear-gradient(135deg, #fff3e0 0%, #ffe0b2 100%)',
    borderRadius: '12px',
    border: '1px solid #ffb74d',
  },
  requestsTitle: {
    fontSize: '1.3rem',
    color: '#e65100',
    marginBottom: '0.5rem',
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
  },
  requestsSubtitle: {
    color: '#666',
    marginBottom: '1rem',
    fontSize: '0.9rem',
  },
  requestsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(280px, 1fr))',
    gap: '1rem',
  },
  requestCard: {
    background: 'white',
    padding: '1rem',
    borderRadius: '8px',
    boxShadow: '0 2px 8px rgba(0,0,0,0.08)',
  },
  requestHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '0.5rem',
  },
  requestCategory: {
    background: '#fff3e0',
    color: '#e65100',
    padding: '0.2rem 0.6rem',
    borderRadius: '4px',
    fontSize: '0.75rem',
    fontWeight: 600,
  },
  voteBtn: {
    background: '#f5f5f5',
    border: 'none',
    padding: '0.3rem 0.6rem',
    borderRadius: '4px',
    cursor: 'pointer',
    color: '#666',
    fontSize: '0.8rem',
  },
  votedBtn: {
    background: '#4caf50',
    border: 'none',
    padding: '0.3rem 0.6rem',
    borderRadius: '4px',
    cursor: 'pointer',
    color: 'white',
    fontSize: '0.8rem',
  },
  requestTitle: {
    fontSize: '1rem',
    marginBottom: '0.5rem',
    color: '#333',
  },
  requestProblem: {
    fontSize: '0.85rem',
    color: '#666',
    marginBottom: '0.5rem',
    lineHeight: 1.5,
  },
  requestMeta: {
    display: 'flex',
    gap: '1rem',
    fontSize: '0.75rem',
    color: '#999',
  },
  
  // 案例网格
  casesGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(320px, 1fr))',
    gap: '1.5rem',
    padding: '2rem',
    maxWidth: '1400px',
    margin: '0 auto',
  },
  caseCard: {
    background: 'white',
    borderRadius: '16px',
    overflow: 'hidden',
    boxShadow: '0 4px 20px rgba(0,0,0,0.08)',
  },
  caseImage: {
    height: '150px',
    background: 'linear-gradient(135deg, #1a73e8 0%, #0d47a1 100%)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: 'white',
    fontSize: '3rem',
  },
  caseBody: {
    padding: '1.5rem',
  },
  caseDept: {
    display: 'inline-block',
    background: '#e3f2fd',
    color: '#1a73e8',
    padding: '0.3rem 0.8rem',
    borderRadius: '12px',
    fontSize: '0.8rem',
    marginBottom: '0.5rem',
  },
  caseTitle: {
    fontSize: '1.2rem',
    marginBottom: '0.5rem',
  },
  caseDesc: {
    color: '#666',
    fontSize: '0.9rem',
    marginBottom: '1rem',
  },
  caseStats: {
    display: 'flex',
    justifyContent: 'space-around',
    paddingTop: '1rem',
    borderTop: '1px solid #f0f0f0',
  },
  caseStatItem: {
    textAlign: 'center',
  },
  caseStatNum: {
    fontSize: '1.2rem',
    fontWeight: 600,
    color: '#1a73e8',
  },
  caseStatLabel: {
    fontSize: '0.75rem',
    color: '#999',
  },
  
  // 数据看板
  statsOverview: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
    gap: '1.5rem',
    padding: '2rem',
    maxWidth: '1400px',
    margin: '0 auto',
  },
  overviewCard: {
    background: 'white',
    padding: '1.5rem',
    borderRadius: '16px',
    textAlign: 'center',
    boxShadow: '0 4px 20px rgba(0,0,0,0.08)',
  },
  overviewIcon: {
    width: '60px',
    height: '60px',
    background: 'linear-gradient(135deg, #1a73e8 0%, #0d47a1 100%)',
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    margin: '0 auto 1rem',
    color: 'white',
    fontSize: '1.5rem',
  },
  overviewNum: {
    fontSize: '2rem',
    fontWeight: 700,
    color: '#1a237e',
  },
  overviewLabel: {
    color: '#666',
    marginTop: '0.5rem',
  },
  deptGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))',
    gap: '1.5rem',
    padding: '2rem',
    maxWidth: '1400px',
    margin: '0 auto',
  },
  deptCard: {
    background: 'white',
    padding: '1.5rem',
    borderRadius: '16px',
    boxShadow: '0 4px 20px rgba(0,0,0,0.08)',
  },
  deptHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '1rem',
    marginBottom: '1rem',
  },
  deptIcon: {
    width: '45px',
    height: '45px',
    background: '#e3f2fd',
    borderRadius: '12px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#1a73e8',
    fontSize: '1.2rem',
  },
  deptName: {
    fontSize: '1.1rem',
    fontWeight: 600,
  },
  deptProgress: {
    marginBottom: '1rem',
  },
  progressBar: {
    height: '10px',
    background: '#e8eaf6',
    borderRadius: '5px',
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    background: 'linear-gradient(90deg, #1a73e8, #ff6b35)',
    borderRadius: '5px',
  },
  progressLabel: {
    display: 'flex',
    justifyContent: 'space-between',
    marginTop: '0.5rem',
    fontSize: '0.85rem',
    color: '#666',
  },
  deptStats: {
    display: 'flex',
    justifyContent: 'space-around',
  },
  deptStatItem: {
    textAlign: 'center',
  },
  deptStatNum: {
    fontSize: '1.3rem',
    fontWeight: 600,
    color: '#1a73e8',
  },
  deptStatLabel: {
    fontSize: '0.75rem',
    color: '#999',
  },
  
  // 帮助中心
  helpGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))',
    gap: '1.5rem',
    padding: '2rem',
    maxWidth: '1200px',
    margin: '0 auto',
  },
  helpCard: {
    background: 'linear-gradient(135deg, #f0f4ff 0%, #e3f2fd 100%)',
    padding: '2rem',
    borderRadius: '16px',
    textAlign: 'center',
    cursor: 'pointer',
    transition: 'all 0.3s',
  },
  helpIcon: {
    width: '70px',
    height: '70px',
    background: 'white',
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    margin: '0 auto 1rem',
    color: '#1a73e8',
    fontSize: '1.8rem',
  },
  helpTitle: {
    fontSize: '1.2rem',
    fontWeight: 600,
    marginBottom: '0.5rem',
  },
  helpDesc: {
    color: '#666',
    fontSize: '0.9rem',
  },
  installSection: {
    background: 'linear-gradient(135deg, #1a237e 0%, #0d47a1 100%)',
    color: 'white',
    padding: '3rem 2rem',
    textAlign: 'center',
    marginTop: '2rem',
  },
  installTitle: {
    fontSize: '1.8rem',
    marginBottom: '0.5rem',
  },
  installDesc: {
    opacity: 0.9,
    marginBottom: '2rem',
  },
  
  // 个人中心
  profileCard: {
    background: 'white',
    padding: '2rem',
    borderRadius: '16px',
    display: 'flex',
    alignItems: 'center',
    gap: '1.5rem',
    maxWidth: '800px',
    margin: '0 auto 2rem',
    boxShadow: '0 4px 20px rgba(0,0,0,0.08)',
  },
  profileAvatar: {
    width: '80px',
    height: '80px',
    background: 'linear-gradient(135deg, #1a73e8 0%, #0d47a1 100%)',
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: 'white',
    fontSize: '2rem',
    fontWeight: 600,
  },
  profileInfo: {},
  
  // 个人中心二级菜单
  profileTabs: {
    display: 'flex',
    gap: '1rem',
    marginBottom: '1.5rem',
    maxWidth: '800px',
    margin: '0 auto 1.5rem',
  },
  profileTab: {
    flex: 1,
    padding: '1rem',
    background: 'white',
    border: '2px solid #e0e0e0',
    borderRadius: '12px',
    cursor: 'pointer',
    fontSize: '1rem',
    fontWeight: 600,
    color: '#666',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.5rem',
    transition: 'all 0.3s',
  },
  profileTabActive: {
    flex: 1,
    padding: '1rem',
    background: 'linear-gradient(135deg, #1a73e8 0%, #0d47a1 100%)',
    border: '2px solid #1a73e8',
    borderRadius: '12px',
    cursor: 'pointer',
    fontSize: '1rem',
    fontWeight: 600,
    color: 'white',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.5rem',
  },
  
  // 团队统计
  teamStats: {
    display: 'grid',
    gridTemplateColumns: 'repeat(4, 1fr)',
    gap: '1rem',
    marginBottom: '1.5rem',
  },
  teamStatItem: {
    background: 'linear-gradient(135deg, #f5f5f5 0%, #eeeeee 100%)',
    padding: '1rem',
    borderRadius: '12px',
    textAlign: 'center',
  },
  teamStatNum: {
    fontSize: '1.8rem',
    fontWeight: 700,
    color: '#1a73e8',
  },
  teamStatLabel: {
    fontSize: '0.85rem',
    color: '#666',
    marginTop: '0.3rem',
  },
  
  // 团队排序
  teamSortBar: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    marginBottom: '1rem',
  },
  teamSortLabel: {
    fontSize: '0.9rem',
    color: '#666',
    marginRight: '0.5rem',
  },
  sortBtn: {
    padding: '0.4rem 0.8rem',
    background: '#f5f5f5',
    border: '1px solid #ddd',
    borderRadius: '6px',
    cursor: 'pointer',
    fontSize: '0.85rem',
    color: '#666',
    display: 'flex',
    alignItems: 'center',
    gap: '0.3rem',
  },
  sortBtnActive: {
    padding: '0.4rem 0.8rem',
    background: '#1a73e8',
    border: '1px solid #1a73e8',
    borderRadius: '6px',
    cursor: 'pointer',
    fontSize: '0.85rem',
    color: 'white',
    display: 'flex',
    alignItems: 'center',
    gap: '0.3rem',
  },
  
  // 团队表格
  teamTable: {
    background: 'white',
    borderRadius: '12px',
    overflow: 'hidden',
    boxShadow: '0 2px 8px rgba(0,0,0,0.08)',
  },
  teamTableHeader: {
    display: 'grid',
    gridTemplateColumns: '2fr 1fr 1fr 1fr',
    background: '#f5f5f5',
    padding: '1rem',
    fontWeight: 600,
    color: '#333',
  },
  teamTableRow: {
    display: 'grid',
    gridTemplateColumns: '2fr 1fr 1fr 1fr',
    padding: '1rem',
    borderBottom: '1px solid #f0f0f0',
    alignItems: 'center',
  },
  teamTh: {
    fontWeight: 600,
    color: '#333',
  },
  teamTd: {
    display: 'flex',
    alignItems: 'center',
  },
  teamAvatar: {
    width: '40px',
    height: '40px',
    background: 'linear-gradient(135deg, #1a73e8 0%, #0d47a1 100%)',
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: 'white',
    fontWeight: 600,
    marginRight: '0.8rem',
  },
  teamName: {
    fontWeight: 600,
    color: '#333',
  },
  teamDept: {
    fontSize: '0.8rem',
    color: '#999',
  },
  installedBadge: {
    background: '#e8f5e9',
    color: '#2e7d32',
    padding: '0.3rem 0.6rem',
    borderRadius: '4px',
    fontSize: '0.8rem',
    display: 'flex',
    alignItems: 'center',
    gap: '0.3rem',
  },
  notInstalledBadge: {
    background: '#ffebee',
    color: '#c62828',
    padding: '0.3rem 0.6rem',
    borderRadius: '4px',
    fontSize: '0.8rem',
    display: 'flex',
    alignItems: 'center',
    gap: '0.3rem',
  },
  taskCount: {
    fontSize: '1.1rem',
    fontWeight: 600,
    color: '#1a73e8',
  },
  caseCount: {
    fontSize: '1.1rem',
    fontWeight: 600,
    color: '#ff9800',
  },
  
  tokenSection: {
    background: 'white',
    padding: '2rem',
    borderRadius: '16px',
    maxWidth: '800px',
    margin: '0 auto',
    boxShadow: '0 4px 20px rgba(0,0,0,0.08)',
  },
  sectionTitle: {
    fontSize: '1.3rem',
    marginBottom: '1.5rem',
    color: '#1a237e',
  },
  tokenCards: {
    display: 'flex',
    flexDirection: 'column',
    gap: '1rem',
    marginBottom: '1.5rem',
  },
  tokenCard: {
    padding: '1rem',
    background: '#f8f9fa',
    borderRadius: '12px',
  },
  tokenLabel: {
    fontWeight: 600,
    marginBottom: '0.3rem',
  },
  tokenDesc: {
    fontSize: '0.8rem',
    color: '#999',
    marginBottom: '0.5rem',
  },
  tokenProgress: {
    marginBottom: '0.5rem',
  },
  tokenInfo: {
    display: 'flex',
    justifyContent: 'space-between',
    fontSize: '0.85rem',
    color: '#666',
  },
  applyBtn: {
    width: '100%',
    padding: '0.8rem',
    background: 'linear-gradient(135deg, #1a73e8 0%, #0d47a1 100%)',
    color: 'white',
    border: 'none',
    borderRadius: '8px',
    cursor: 'pointer',
    fontWeight: 600,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.5rem',
  },
  
  // 团队统计
  teamStats: {
    display: 'grid',
    gridTemplateColumns: 'repeat(4, 1fr)',
    gap: '1rem',
    marginBottom: '1.5rem',
  },
  teamStatItem: {
    background: 'linear-gradient(135deg, #f5f5f5 0%, #eeeeee 100%)',
    padding: '1rem',
    borderRadius: '12px',
    textAlign: 'center',
  },
  teamStatNum: {
    fontSize: '1.8rem',
    fontWeight: 700,
    color: '#1a73e8',
  },
  teamStatLabel: {
    fontSize: '0.85rem',
    color: '#666',
    marginTop: '0.3rem',
  },
  
  // 团队排序
  teamSortBar: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    marginBottom: '1rem',
  },
  teamSortLabel: {
    fontSize: '0.9rem',
    color: '#666',
    marginRight: '0.5rem',
  },
  sortBtn: {
    padding: '0.4rem 0.8rem',
    background: '#f5f5f5',
    border: '1px solid #ddd',
    borderRadius: '6px',
    cursor: 'pointer',
    fontSize: '0.85rem',
    color: '#666',
    display: 'flex',
    alignItems: 'center',
    gap: '0.3rem',
  },
  sortBtnActive: {
    padding: '0.4rem 0.8rem',
    background: '#1a73e8',
    border: '1px solid #1a73e8',
    borderRadius: '6px',
    cursor: 'pointer',
    fontSize: '0.85rem',
    color: 'white',
    display: 'flex',
    alignItems: 'center',
    gap: '0.3rem',
  },
  
  // 团队表格
  teamTable: {
    background: 'white',
    borderRadius: '12px',
    overflow: 'hidden',
    boxShadow: '0 2px 8px rgba(0,0,0,0.08)',
  },
  teamTableHeader: {
    display: 'grid',
    gridTemplateColumns: '2fr 1fr 1fr 1fr',
    background: '#f5f5f5',
    padding: '1rem',
    fontWeight: 600,
    color: '#333',
  },
  teamTableRow: {
    display: 'grid',
    gridTemplateColumns: '2fr 1fr 1fr 1fr',
    padding: '1rem',
    borderBottom: '1px solid #f0f0f0',
    alignItems: 'center',
  },
  teamTh: {
    fontWeight: 600,
    color: '#333',
  },
  teamTd: {
    display: 'flex',
    alignItems: 'center',
  },
  teamAvatar: {
    width: '40px',
    height: '40px',
    background: 'linear-gradient(135deg, #1a73e8 0%, #0d47a1 100%)',
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: 'white',
    fontWeight: 600,
    marginRight: '0.8rem',
  },
  teamName: {
    fontWeight: 600,
    color: '#333',
  },
  teamDept: {
    fontSize: '0.8rem',
    color: '#999',
  },
  installedBadge: {
    background: '#e8f5e9',
    color: '#2e7d32',
    padding: '0.3rem 0.6rem',
    borderRadius: '4px',
    fontSize: '0.8rem',
    display: 'flex',
    alignItems: 'center',
    gap: '0.3rem',
  },
  notInstalledBadge: {
    background: '#ffebee',
    color: '#c62828',
    padding: '0.3rem 0.6rem',
    borderRadius: '4px',
    fontSize: '0.8rem',
    display: 'flex',
    alignItems: 'center',
    gap: '0.3rem',
  },
  taskCount: {
    fontSize: '1.1rem',
    fontWeight: 600,
    color: '#1a73e8',
  },
  caseCount: {
    fontSize: '1.1rem',
    fontWeight: 600,
    color: '#ff9800',
  },
  
  // 流量奖励区域
  rewardSection: {
    marginBottom: '1rem',
    background: 'linear-gradient(135deg, #e8f5e9 0%, #c8e6c9 100%)',
    borderRadius: '8px',
    padding: '1rem',
    border: '1px solid #4caf50',
  },
  rewardContent: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  rewardText: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    color: '#2e7d32',
    fontSize: '0.95rem',
  },
  rewardBtn: {
    background: '#4caf50',
    color: 'white',
    border: 'none',
    padding: '0.5rem 1rem',
    borderRadius: '6px',
    cursor: 'pointer',
    fontWeight: 600,
    display: 'flex',
    alignItems: 'center',
    gap: '0.3rem',
  },
  
  // 审批提示
  approvalInfo: {
    background: '#fff3e0',
    color: '#e65100',
    padding: '0.8rem',
    borderRadius: '6px',
    marginBottom: '1rem',
    fontSize: '0.9rem',
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
  },
  
  // 管理员后台
  adminTabs: {
    display: 'flex',
    gap: '0.5rem',
    padding: '1rem 2rem',
    background: 'white',
    borderBottom: '1px solid #e0e0e0',
  },
  adminTab: {
    padding: '0.7rem 1.2rem',
    background: 'none',
    border: 'none',
    color: '#666',
    borderBottom: '2px solid transparent',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
  },
  adminTabActive: {
    padding: '0.7rem 1.2rem',
    background: 'none',
    border: 'none',
    color: '#1a73e8',
    borderBottom: '2px solid #1a73e8',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
  },
  badge: {
    background: '#ff6b35',
    color: 'white',
    padding: '0.2rem 0.5rem',
    borderRadius: '10px',
    fontSize: '0.7rem',
  },
  adminContent: {
    padding: '2rem',
  },
  adminTitle: {
    fontSize: '1.3rem',
    marginBottom: '1rem',
    color: '#1a237e',
  },
  table: {
    width: '100%',
    background: 'white',
    borderRadius: '12px',
    overflow: 'hidden',
    boxShadow: '0 4px 20px rgba(0,0,0,0.08)',
  },
  approveBtn: {
    padding: '0.4rem 0.8rem',
    background: '#28a745',
    color: 'white',
    border: 'none',
    borderRadius: '5px',
    cursor: 'pointer',
    marginRight: '0.5rem',
  },
  rejectBtn: {
    padding: '0.4rem 0.8rem',
    background: '#dc3545',
    color: 'white',
    border: 'none',
    borderRadius: '5px',
    cursor: 'pointer',
    marginRight: '0.5rem',
  },
  viewBtn: {
    padding: '0.4rem 0.8rem',
    background: '#1a73e8',
    color: 'white',
    border: 'none',
    borderRadius: '5px',
    cursor: 'pointer',
  },
  actionBtn: {
    padding: '0.4rem 0.8rem',
    background: '#e3f2fd',
    color: '#1a73e8',
    border: 'none',
    borderRadius: '5px',
    cursor: 'pointer',
    marginRight: '0.5rem',
  },
  offlineBtn: {
    padding: '0.4rem 0.8rem',
    background: '#ffc107',
    color: '#333',
    border: 'none',
    borderRadius: '5px',
    cursor: 'pointer',
  },
  roleTag: {
    padding: '0.3rem 0.6rem',
    background: '#e3f2fd',
    color: '#1a73e8',
    borderRadius: '12px',
    fontSize: '0.8rem',
  },
  statusPublished: {
    padding: '0.3rem 0.6rem',
    background: '#d4edda',
    color: '#155724',
    borderRadius: '12px',
    fontSize: '0.8rem',
  },
  statusPending: {
    padding: '0.3rem 0.6rem',
    background: '#fff3cd',
    color: '#856404',
    borderRadius: '12px',
    fontSize: '0.8rem',
  },
  tokenForm: {
    background: 'white',
    padding: '2rem',
    borderRadius: '12px',
    display: 'flex',
    gap: '1rem',
    flexWrap: 'wrap',
    boxShadow: '0 4px 20px rgba(0,0,0,0.08)',
  },
  formInput: {
    padding: '0.6rem 1rem',
    border: '1px solid #ddd',
    borderRadius: '8px',
    fontSize: '0.9rem',
  },
  formSelect: {
    padding: '0.6rem 1rem',
    border: '1px solid #ddd',
    borderRadius: '8px',
    fontSize: '0.9rem',
  },
  submitBtn: {
    padding: '0.6rem 1.5rem',
    background: 'linear-gradient(135deg, #1a73e8 0%, #0d47a1 100%)',
    color: 'white',
    border: 'none',
    borderRadius: '8px',
    cursor: 'pointer',
    fontWeight: 600,
  },
  
  // 登录页
  loginPage: {
    minHeight: '100vh',
    background: 'linear-gradient(135deg, #0a0a2e 0%, #1a1a5e 50%, #0d1b2a 100%)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '2rem',
  },
  loginCard: {
    background: 'white',
    padding: '3rem',
    borderRadius: '20px',
    maxWidth: '400px',
    width: '100%',
    textAlign: 'center',
    boxShadow: '0 20px 60px rgba(0,0,0,0.3)',
  },
  loginLogo: {
    fontSize: '4rem',
    color: '#ff6b35',
    marginBottom: '1rem',
  },
  loginTitle: {
    fontSize: '1.8rem',
    color: '#1a237e',
    marginBottom: '0.5rem',
  },
  loginSubtitle: {
    color: '#666',
    marginBottom: '2rem',
  },
  loginForm: {
    display: 'flex',
    flexDirection: 'column',
    gap: '1rem',
  },
  loginInput: {
    padding: '0.8rem 1rem',
    border: '1px solid #ddd',
    borderRadius: '10px',
    fontSize: '1rem',
  },
  loginBtn: {
    padding: '0.8rem',
    background: 'linear-gradient(135deg, #ff6b35 0%, #e55a2b 100%)',
    color: 'white',
    border: 'none',
    borderRadius: '10px',
    cursor: 'pointer',
    fontSize: '1rem',
    fontWeight: 600,
    marginTop: '1rem',
  },
  loginTips: {
    marginTop: '2rem',
    padding: '1rem',
    background: '#f8f9fa',
    borderRadius: '10px',
    fontSize: '0.85rem',
    color: '#666',
    textAlign: 'left',
  },
  
  // 技能详情页
  backBtn: {
    padding: '0.6rem 1.2rem',
    background: 'white',
    border: '1px solid #ddd',
    borderRadius: '8px',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    marginBottom: '1.5rem',
    fontSize: '0.9rem',
    color: '#666',
  },
  detailHeader: {
    background: 'white',
    padding: '2rem',
    borderRadius: '16px',
    display: 'flex',
    alignItems: 'flex-start',
    gap: '1.5rem',
    marginBottom: '1.5rem',
    boxShadow: '0 4px 20px rgba(0,0,0,0.08)',
  },
  detailIcon: {
    width: '80px',
    height: '80px',
    background: 'linear-gradient(135deg, #1a73e8 0%, #0d47a1 100%)',
    borderRadius: '16px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: 'white',
    fontSize: '2rem',
    flexShrink: 0,
  },
  detailInfo: {
    flex: 1,
  },
  detailTitle: {
    fontSize: '1.8rem',
    color: '#1a237e',
    marginBottom: '0.3rem',
  },
  detailSubtitle: {
    color: '#666',
    fontSize: '0.95rem',
    marginBottom: '1rem',
  },
  detailMeta: {
    display: 'flex',
    gap: '1rem',
    marginBottom: '1rem',
    flexWrap: 'wrap',
  },
  detailTag: {
    color: '#666',
    fontSize: '0.85rem',
    display: 'flex',
    alignItems: 'center',
    gap: '0.3rem',
  },
  detailTags: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '0.5rem',
  },
  detailActions: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.8rem',
  },
  secondaryBtn: {
    padding: '0.8rem 1.5rem',
    background: '#f0f4ff',
    color: '#1a73e8',
    border: 'none',
    borderRadius: '8px',
    cursor: 'pointer',
    fontWeight: 600,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.5rem',
  },
  detailContent: {
    display: 'grid',
    gridTemplateColumns: '1fr 320px',
    gap: '1.5rem',
    padding: '0 2rem 2rem',
    maxWidth: '1400px',
    margin: '0 auto',
  },
  detailMain: {
    display: 'flex',
    flexDirection: 'column',
    gap: '1.5rem',
  },
  detailSection: {
    background: 'white',
    padding: '1.5rem',
    borderRadius: '16px',
    boxShadow: '0 4px 20px rgba(0,0,0,0.08)',
  },
  sectionTitle: {
    fontSize: '1.2rem',
    color: '#1a237e',
    marginBottom: '1rem',
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
  },
  detailDesc: {
    color: '#555',
    lineHeight: 1.8,
    fontSize: '0.95rem',
  },
  featuresList: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
    gap: '0.8rem',
  },
  featureItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    color: '#555',
    padding: '0.5rem',
    background: '#f8f9fa',
    borderRadius: '8px',
  },
  useSteps: {
    display: 'flex',
    flexDirection: 'column',
    gap: '1rem',
  },
  useStep: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: '1rem',
  },
  stepNumber: {
    width: '28px',
    height: '28px',
    background: 'linear-gradient(135deg, #1a73e8 0%, #0d47a1 100%)',
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: 'white',
    fontSize: '0.85rem',
    fontWeight: 600,
    flexShrink: 0,
  },
  stepText: {
    color: '#555',
    lineHeight: 1.6,
    paddingTop: '0.2rem',
  },
  
  // 评论
  commentForm: {
    marginBottom: '1.5rem',
    paddingBottom: '1.5rem',
    borderBottom: '1px solid #f0f0f0',
  },
  ratingSelect: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    marginBottom: '1rem',
  },
  starBtn: {
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    fontSize: '1.2rem',
    color: '#ddd',
    padding: '0.2rem',
  },
  starActive: {
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    fontSize: '1.2rem',
    color: '#ffc107',
    padding: '0.2rem',
  },
  commentInput: {
    width: '100%',
    padding: '0.8rem',
    border: '1px solid #ddd',
    borderRadius: '8px',
    fontSize: '0.95rem',
    resize: 'vertical',
    fontFamily: 'inherit',
    marginBottom: '1rem',
  },
  commentsList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '1rem',
  },
  commentCard: {
    display: 'flex',
    gap: '1rem',
    padding: '1rem',
    background: '#f8f9fa',
    borderRadius: '12px',
  },
  commentAvatar: {
    width: '40px',
    height: '40px',
    background: 'linear-gradient(135deg, #1a73e8 0%, #0d47a1 100%)',
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: 'white',
    fontWeight: 600,
    flexShrink: 0,
  },
  commentContent: {
    flex: 1,
  },
  commentHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.8rem',
    marginBottom: '0.5rem',
  },
  commentUser: {
    fontWeight: 600,
    color: '#1a237e',
  },
  commentRating: {
    display: 'flex',
    gap: '0.1rem',
  },
  starFilled: {
    color: '#ffc107',
    fontSize: '0.8rem',
  },
  starEmpty: {
    color: '#ddd',
    fontSize: '0.8rem',
  },
  commentText: {
    color: '#555',
    fontSize: '0.9rem',
    lineHeight: 1.5,
    marginBottom: '0.5rem',
  },
  commentDate: {
    fontSize: '0.8rem',
    color: '#999',
  },
  noComments: {
    textAlign: 'center',
    color: '#999',
    padding: '2rem',
  },
  
  // 侧边栏
  detailSidebar: {
    display: 'flex',
    flexDirection: 'column',
    gap: '1rem',
  },
  sidebarCard: {
    background: 'white',
    padding: '1.5rem',
    borderRadius: '16px',
    boxShadow: '0 4px 20px rgba(0,0,0,0.08)',
  },
  sidebarTitle: {
    fontSize: '1.1rem',
    color: '#1a237e',
    marginBottom: '1rem',
    paddingBottom: '0.8rem',
    borderBottom: '1px solid #f0f0f0',
  },
  infoList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.8rem',
  },
  infoItem: {
    display: 'flex',
    justifyContent: 'space-between',
  },
  infoLabel: {
    color: '#666',
    fontSize: '0.9rem',
  },
  infoValue: {
    color: '#1a237e',
    fontWeight: 600,
    fontSize: '0.9rem',
  },
  hotSkills: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.8rem',
  },
  hotSkillItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.8rem',
    padding: '0.6rem',
    background: '#f8f9fa',
    borderRadius: '8px',
    color: '#555',
    cursor: 'pointer',
    transition: 'all 0.2s',
  },
  
  // 投稿按钮
  submitCaseBtnContainer: {
    padding: '0 2rem 1rem',
    textAlign: 'right',
    maxWidth: '1400px',
    margin: '0 auto',
  },
  submitCaseBtn: {
    padding: '0.8rem 1.5rem',
    background: 'linear-gradient(135deg, #ff6b35 0%, #e55a2b 100%)',
    color: 'white',
    border: 'none',
    borderRadius: '8px',
    cursor: 'pointer',
    fontWeight: 600,
    display: 'inline-flex',
    alignItems: 'center',
    gap: '0.5rem',
    fontSize: '0.95rem',
  },
  
  // 投稿表单
  submitFormCard: {
    background: 'white',
    padding: '2rem',
    borderRadius: '16px',
    maxWidth: '800px',
    margin: '0 auto 2rem',
    boxShadow: '0 4px 20px rgba(0,0,0,0.08)',
  },
  submitFormTitle: {
    fontSize: '1.5rem',
    color: '#1a237e',
    marginBottom: '0.5rem',
    textAlign: 'center',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.5rem',
  },
  submitFormSubtitle: {
    color: '#666',
    textAlign: 'center',
    marginBottom: '2rem',
  },
  submitForm: {
    display: 'flex',
    flexDirection: 'column',
    gap: '1.2rem',
  },
  formGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.5rem',
  },
  formRow: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '1rem',
  },
  formLabel: {
    fontWeight: 600,
    color: '#333',
    fontSize: '0.95rem',
  },
  required: {
    color: '#dc3545',
  },
  formInput: {
    padding: '0.8rem 1rem',
    border: '1px solid #ddd',
    borderRadius: '8px',
    fontSize: '0.95rem',
    fontFamily: 'inherit',
  },
  formSelect: {
    padding: '0.8rem 1rem',
    border: '1px solid #ddd',
    borderRadius: '8px',
    fontSize: '0.95rem',
    fontFamily: 'inherit',
    background: 'white',
  },
  formTextarea: {
    padding: '0.8rem 1rem',
    border: '1px solid #ddd',
    borderRadius: '8px',
    fontSize: '0.95rem',
    fontFamily: 'inherit',
    resize: 'vertical',
  },
  uploadArea: {
    position: 'relative',
  },
  fileInput: {
    position: 'absolute',
    width: '0',
    height: '0',
    opacity: 0,
  },
  uploadLabel: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '2rem',
    border: '2px dashed #ddd',
    borderRadius: '12px',
    cursor: 'pointer',
    color: '#666',
    transition: 'all 0.3s',
    gap: '0.5rem',
  },
  previewGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(120px, 1fr))',
    gap: '1rem',
    marginTop: '1rem',
  },
  previewItem: {
    position: 'relative',
    borderRadius: '8px',
    overflow: 'hidden',
  },
  previewImage: {
    width: '100%',
    height: '100px',
    objectFit: 'cover',
    borderRadius: '8px',
  },
  removeImageBtn: {
    position: 'absolute',
    top: '5px',
    right: '5px',
    width: '24px',
    height: '24px',
    background: 'rgba(0,0,0,0.6)',
    color: 'white',
    border: 'none',
    borderRadius: '50%',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '0.8rem',
  },
  formActions: {
    display: 'flex',
    gap: '1rem',
    marginTop: '1rem',
  },
  cancelBtn: {
    flex: 1,
    padding: '0.8rem',
    background: '#f0f0f0',
    color: '#666',
    border: 'none',
    borderRadius: '8px',
    cursor: 'pointer',
    fontWeight: 600,
  },
  
  // 成功页面
  successCard: {
    background: 'white',
    padding: '4rem 2rem',
    borderRadius: '16px',
    textAlign: 'center',
    maxWidth: '500px',
    margin: '2rem auto',
    boxShadow: '0 4px 20px rgba(0,0,0,0.08)',
  },
  successIcon: {
    fontSize: '5rem',
    color: '#28a745',
    marginBottom: '1.5rem',
  },
  successTitle: {
    fontSize: '1.8rem',
    color: '#1a237e',
    marginBottom: '1rem',
  },
  successText: {
    color: '#666',
    marginBottom: '2rem',
    lineHeight: 1.6,
  },
  
  // 提示框
  noticeBox: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.8rem',
    padding: '1rem',
    background: '#fff3cd',
    borderRadius: '8px',
    marginBottom: '1.5rem',
    color: '#856404',
  },
  
  // 用户技能列表
  userSkillsList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '1rem',
  },
  userSkillItem: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '1rem',
    background: '#f8f9fa',
    borderRadius: '12px',
  },
  userSkillInfo: {
    display: 'flex',
    alignItems: 'center',
    gap: '1rem',
  },
  userSkillIcon: {
    width: '40px',
    height: '40px',
    background: 'linear-gradient(135deg, #1a73e8 0%, #0d47a1 100%)',
    borderRadius: '10px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: 'white',
  },
  userSkillName: {
    fontWeight: 600,
    color: '#1a237e',
    marginBottom: '0.3rem',
  },
  userSkillMeta: {
    display: 'flex',
    gap: '1rem',
    fontSize: '0.85rem',
  },
  downloadCount: {
    color: '#666',
  },
  userSkillActions: {
    display: 'flex',
    gap: '0.5rem',
  },
  
  // 周期选择
  chartPeriodSelect: {
    display: 'flex',
    gap: '0.5rem',
    marginBottom: '1.5rem',
  },
  periodBtn: {
    padding: '0.5rem 1rem',
    background: '#f0f4ff',
    border: 'none',
    color: '#1a73e8',
    borderRadius: '20px',
    cursor: 'pointer',
    fontSize: '0.85rem',
  },
  periodBtnActive: {
    padding: '0.5rem 1rem',
    background: 'linear-gradient(135deg, #1a73e8 0%, #0d47a1 100%)',
    border: 'none',
    color: 'white',
    borderRadius: '20px',
    cursor: 'pointer',
    fontSize: '0.85rem',
  },
  
  // 图表
  chartContainer: {
    background: '#f8f9fa',
    borderRadius: '12px',
    padding: '1.5rem',
    marginBottom: '1rem',
  },
  chart: {
    display: 'flex',
    alignItems: 'flex-end',
    justifyContent: 'space-around',
    height: '200px',
    gap: '0.5rem',
  },
  chartBar: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    height: '100%',
    justifyContent: 'flex-end',
  },
  barFill: {
    width: '80%',
    background: 'linear-gradient(180deg, #1a73e8 0%, #0d47a1 100%)',
    borderRadius: '4px 4px 0 0',
    minHeight: '10px',
    transition: 'height 0.3s',
  },
  barLabel: {
    fontSize: '0.7rem',
    color: '#666',
    marginTop: '0.5rem',
    textAlign: 'center',
  },
  
  // 累计任务
  totalTasks: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '1rem',
    background: 'linear-gradient(135deg, #1a237e 0%, #0d47a1 100%)',
    borderRadius: '12px',
    color: 'white',
  },
  totalTasksNum: {
    fontSize: '1.5rem',
    fontWeight: 700,
  },
  
  // 排行榜
  leaderboardSection: {
    padding: '2rem',
    maxWidth: '1400px',
    margin: '0 auto',
  },
  leaderboardHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '1.5rem',
  },
  leaderboardTitle: {
    fontSize: '1.5rem',
    color: '#1a237e',
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
  },
  periodTabs: {
    display: 'flex',
    gap: '0.5rem',
  },
  periodTab: {
    padding: '0.5rem 1rem',
    background: '#f0f4ff',
    border: 'none',
    color: '#1a73e8',
    borderRadius: '20px',
    cursor: 'pointer',
    fontSize: '0.85rem',
  },
  periodTabActive: {
    padding: '0.5rem 1rem',
    background: 'linear-gradient(135deg, #1a73e8 0%, #0d47a1 100%)',
    border: 'none',
    color: 'white',
    borderRadius: '20px',
    cursor: 'pointer',
    fontSize: '0.85rem',
  },
  leaderboardGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(320px, 1fr))',
    gap: '1.5rem',
  },
  leaderboardCard: {
    background: 'white',
    borderRadius: '16px',
    padding: '1.5rem',
    boxShadow: '0 4px 20px rgba(0,0,0,0.08)',
  },
  leaderboardCardTitle: {
    fontSize: '1.1rem',
    color: '#1a237e',
    marginBottom: '1rem',
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
  },
  leaderboardList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.8rem',
  },
  leaderboardItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.8rem',
    padding: '0.8rem',
    background: '#f8f9fa',
    borderRadius: '10px',
  },
  rankBadge: {
    width: '28px',
    height: '28px',
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#333',
    fontWeight: 700,
    fontSize: '0.85rem',
    flexShrink: 0,
  },
  avatar: {
    width: '36px',
    height: '36px',
    background: 'linear-gradient(135deg, #1a73e8 0%, #0d47a1 100%)',
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: 'white',
    fontWeight: 600,
    fontSize: '0.9rem',
    flexShrink: 0,
  },
  leaderboardInfo: {
    flex: 1,
  },
  leaderboardFullInfo: {
    flex: 1,
  },
  leaderboardName: {
    fontWeight: 600,
    color: '#333',
    fontSize: '0.95rem',
  },
  leaderboardDept: {
    fontSize: '0.8rem',
    color: '#666',
  },
  leaderboardValue: {
    fontWeight: 700,
    color: '#1a73e8',
    fontSize: '1.1rem',
  },
  
  // 投稿按钮
  submitSkillBtn: {
    background: 'linear-gradient(135deg, #ff6b35 0%, #f7931e 100%)',
    color: 'white',
    border: 'none',
    padding: '0.6rem 1.2rem',
    borderRadius: '20px',
    cursor: 'pointer',
    fontSize: '0.95rem',
    fontWeight: 600,
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    transition: 'transform 0.2s',
  },
  
  // 提示框
  noticeBox: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.8rem',
    padding: '1rem',
    background: '#fff3cd',
    borderRadius: '8px',
    marginBottom: '1.5rem',
    color: '#856404',
  },
  
  // 投稿表单
  submitFormCard: {
    background: 'white',
    borderRadius: '16px',
    padding: '2rem',
    maxWidth: '800px',
    margin: '0 auto',
    boxShadow: '0 4px 20px rgba(0,0,0,0.08)',
  },
  submitFormTitle: {
    fontSize: '1.8rem',
    color: '#1a237e',
    marginBottom: '0.5rem',
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
  },
  submitFormSubtitle: {
    color: '#666',
    marginBottom: '1.5rem',
  },
  submitForm: {
    display: 'flex',
    flexDirection: 'column',
    gap: '1.2rem',
  },
  formRow: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '1rem',
  },
  formGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.5rem',
  },
  formLabel: {
    fontWeight: 600,
    color: '#333',
    fontSize: '0.95rem',
  },
  required: {
    color: '#e74c3c',
  },
  formInput: {
    padding: '0.8rem 1rem',
    border: '1px solid #ddd',
    borderRadius: '8px',
    fontSize: '1rem',
    outline: 'none',
    transition: 'border-color 0.2s',
  },
  formSelect: {
    padding: '0.8rem 1rem',
    border: '1px solid #ddd',
    borderRadius: '8px',
    fontSize: '1rem',
    outline: 'none',
    background: 'white',
  },
  formTextarea: {
    padding: '0.8rem 1rem',
    border: '1px solid #ddd',
    borderRadius: '8px',
    fontSize: '1rem',
    outline: 'none',
    resize: 'vertical',
    fontFamily: 'inherit',
  },
  formActions: {
    display: 'flex',
    justifyContent: 'flex-end',
    gap: '1rem',
    marginTop: '1rem',
  },
  cancelBtn: {
    padding: '0.8rem 1.5rem',
    background: '#f0f0f0',
    border: 'none',
    borderRadius: '8px',
    cursor: 'pointer',
    fontSize: '1rem',
    color: '#666',
  },
  submitBtn: {
    padding: '0.8rem 1.5rem',
    background: 'linear-gradient(135deg, #1a73e8 0%, #0d47a1 100%)',
    border: 'none',
    borderRadius: '8px',
    cursor: 'pointer',
    fontSize: '1rem',
    color: 'white',
    fontWeight: 600,
  },
  
  // 用户技能列表
  userSkillsList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '1rem',
  },
  userSkillItem: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '1rem',
    background: '#f8f9fa',
    borderRadius: '12px',
  },
  userSkillInfo: {
    display: 'flex',
    alignItems: 'center',
    gap: '1rem',
  },
  userSkillIcon: {
    width: '40px',
    height: '40px',
    background: 'linear-gradient(135deg, #1a73e8 0%, #0d47a1 100%)',
    borderRadius: '10px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: 'white',
  },
  userSkillName: {
    fontWeight: 600,
    color: '#1a237e',
    marginBottom: '0.3rem',
  },
  userSkillMeta: {
    display: 'flex',
    gap: '1rem',
    fontSize: '0.85rem',
    alignItems: 'center',
  },
  downloadCount: {
    color: '#666',
  },
  userSkillActions: {
    display: 'flex',
    gap: '0.5rem',
  },
  
  // 状态标签
  statusPublished: {
    color: '#28a745',
    fontWeight: 600,
  },
  statusPending: {
    color: '#ffc107',
    fontWeight: 600,
  },
  excellentBadge: {
    background: 'linear-gradient(135deg, #ffd700 0%, #ffb700 100%)',
    color: '#333',
    padding: '0.2rem 0.5rem',
    borderRadius: '4px',
    fontSize: '0.75rem',
    fontWeight: 700,
    display: 'flex',
    alignItems: 'center',
    gap: '0.2rem',
  },
  submissionDate: {
    color: '#999',
    fontSize: '0.8rem',
  },
  
  // 周期选择
  chartPeriodSelect: {
    display: 'flex',
    gap: '0.5rem',
    marginBottom: '1.5rem',
  },
  periodBtn: {
    padding: '0.5rem 1rem',
    background: '#f0f4ff',
    border: 'none',
    color: '#1a73e8',
    borderRadius: '20px',
    cursor: 'pointer',
    fontSize: '0.85rem',
  },
  periodBtnActive: {
    padding: '0.5rem 1rem',
    background: 'linear-gradient(135deg, #1a73e8 0%, #0d47a1 100%)',
    border: 'none',
    color: 'white',
    borderRadius: '20px',
    cursor: 'pointer',
    fontSize: '0.85rem',
  },
  
  // 图表
  chartContainer: {
    background: '#f8f9fa',
    borderRadius: '12px',
    padding: '1.5rem',
    marginBottom: '1rem',
  },
  chart: {
    display: 'flex',
    alignItems: 'flex-end',
    justifyContent: 'space-around',
    height: '200px',
    gap: '0.5rem',
  },
  chartBar: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    height: '100%',
    justifyContent: 'flex-end',
  },
  barFill: {
    width: '80%',
    background: 'linear-gradient(180deg, #1a73e8 0%, #0d47a1 100%)',
    borderRadius: '4px 4px 0 0',
    minHeight: '10px',
    transition: 'height 0.3s',
  },
  barLabel: {
    fontSize: '0.7rem',
    color: '#666',
    marginTop: '0.5rem',
    textAlign: 'center',
  },
  
  // 累计任务
  totalTasks: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '1rem',
    background: 'linear-gradient(135deg, #1a237e 0%, #0d47a1 100%)',
    borderRadius: '12px',
    color: 'white',
  },
  totalTasksNum: {
    fontSize: '1.5rem',
    fontWeight: 700,
  },
  
  // 排行榜
  leaderboardSection: {
    padding: '2rem',
    maxWidth: '1400px',
    margin: '0 auto',
  },
  leaderboardHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '1.5rem',
  },
  leaderboardTitle: {
    fontSize: '1.5rem',
    color: '#1a237e',
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
  },
  periodTabs: {
    display: 'flex',
    gap: '0.5rem',
  },
  periodTab: {
    padding: '0.5rem 1rem',
    background: '#f0f4ff',
    border: 'none',
    color: '#1a73e8',
    borderRadius: '20px',
    cursor: 'pointer',
    fontSize: '0.85rem',
  },
  periodTabActive: {
    padding: '0.5rem 1rem',
    background: 'linear-gradient(135deg, #1a73e8 0%, #0d47a1 100%)',
    border: 'none',
    color: 'white',
    borderRadius: '20px',
    cursor: 'pointer',
    fontSize: '0.85rem',
  },
  leaderboardGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(320px, 1fr))',
    gap: '1.5rem',
  },
  leaderboardCard: {
    background: 'white',
    borderRadius: '16px',
    padding: '1.5rem',
    boxShadow: '0 4px 20px rgba(0,0,0,0.08)',
  },
  leaderboardCardTitle: {
    fontSize: '1.1rem',
    color: '#1a237e',
    marginBottom: '1rem',
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
  },
  leaderboardList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.8rem',
  },
  leaderboardItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.8rem',
    padding: '0.8rem',
    background: '#f8f9fa',
    borderRadius: '10px',
  },
  
  // 查看按钮
  viewBtn: {
    padding: '0.4rem 0.8rem',
    background: '#1a73e8',
    border: 'none',
    borderRadius: '6px',
    color: 'white',
    cursor: 'pointer',
    fontSize: '0.85rem',
  },
  
  // 成功页面
  successCard: {
    background: 'white',
    padding: '4rem 2rem',
    borderRadius: '16px',
    textAlign: 'center',
    maxWidth: '500px',
    margin: '2rem auto',
    boxShadow: '0 4px 20px rgba(0,0,0,0.08)',
  },
  successIcon: {
    fontSize: '5rem',
    color: '#28a745',
    marginBottom: '1.5rem',
  },
  successTitle: {
    fontSize: '1.8rem',
    color: '#1a237e',
    marginBottom: '1rem',
  },
  successText: {
    color: '#666',
    marginBottom: '2rem',
    lineHeight: 1.6,
  },
  
  // 返回按钮
  backBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '0.5rem',
    padding: '0.6rem 1rem',
    background: '#f0f0f0',
    border: 'none',
    borderRadius: '8px',
    cursor: 'pointer',
    color: '#333',
    fontSize: '0.95rem',
    marginBottom: '1.5rem',
  },
  
  // 安全合规页面
  securityTabs: {
    display: 'flex',
    gap: '1rem',
    marginBottom: '2rem',
    justifyContent: 'center',
  },
  securityTab: {
    padding: '0.8rem 2rem',
    background: 'white',
    border: '2px solid #e0e0e0',
    borderRadius: '30px',
    cursor: 'pointer',
    fontSize: '1rem',
    color: '#666',
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    transition: 'all 0.3s',
  },
  securityTabActive: {
    padding: '0.8rem 2rem',
    background: 'linear-gradient(135deg, #1a73e8 0%, #0d47a1 100%)',
    border: '2px solid #1a73e8',
    borderRadius: '30px',
    cursor: 'pointer',
    fontSize: '1rem',
    color: 'white',
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
  },
  
  // 学习资料
  materialsList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '1.5rem',
  },
  materialCard: {
    background: 'white',
    borderRadius: '16px',
    padding: '1.5rem',
    boxShadow: '0 4px 20px rgba(0,0,0,0.08)',
    display: 'flex',
    gap: '1rem',
  },
  materialIcon: {
    width: '50px',
    height: '50px',
    background: 'linear-gradient(135deg, #1a73e8 0%, #0d47a1 100%)',
    borderRadius: '12px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: 'white',
    fontSize: '1.3rem',
    flexShrink: 0,
  },
  materialContent: {
    flex: 1,
  },
  materialTitle: {
    fontSize: '1.2rem',
    color: '#1a237e',
    marginBottom: '0.8rem',
  },
  materialText: {
    color: '#666',
    lineHeight: 1.8,
    fontSize: '0.95rem',
    whiteSpace: 'pre-wrap',
    fontFamily: 'inherit',
    margin: 0,
  },
  
  // 考试页面
  examIntro: {
    background: 'white',
    borderRadius: '20px',
    padding: '3rem',
    textAlign: 'center',
    boxShadow: '0 4px 20px rgba(0,0,0,0.08)',
    maxWidth: '600px',
    margin: '0 auto',
  },
  examIcon: {
    fontSize: '4rem',
    color: '#1a73e8',
    marginBottom: '1.5rem',
  },
  examTitle: {
    fontSize: '1.8rem',
    color: '#1a237e',
    marginBottom: '0.5rem',
  },
  examDesc: {
    color: '#666',
    fontSize: '1.1rem',
    marginBottom: '2rem',
  },
  examRewards: {
    background: '#f0f4ff',
    borderRadius: '12px',
    padding: '1.5rem',
    marginBottom: '2rem',
  },
  examRewardTitle: {
    fontSize: '1rem',
    color: '#1a73e8',
    marginBottom: '0.8rem',
    fontWeight: 600,
  },
  examRewardItem: {
    color: '#333',
    fontSize: '1.1rem',
    marginBottom: '0.5rem',
  },
  examStartBtn: {
    padding: '1rem 3rem',
    background: 'linear-gradient(135deg, #1a73e8 0%, #0d47a1 100%)',
    border: 'none',
    borderRadius: '30px',
    color: 'white',
    fontSize: '1.2rem',
    fontWeight: 600,
    cursor: 'pointer',
    transition: 'transform 0.2s',
  },
  
  // 考试容器
  examContainer: {
    maxWidth: '700px',
    margin: '0 auto',
  },
  examProgress: {
    textAlign: 'center',
    color: '#666',
    marginBottom: '1rem',
    fontSize: '1.1rem',
  },
  questionCard: {
    background: 'white',
    borderRadius: '16px',
    padding: '2rem',
    boxShadow: '0 4px 20px rgba(0,0,0,0.08)',
    marginBottom: '1.5rem',
  },
  questionText: {
    fontSize: '1.2rem',
    color: '#1a237e',
    marginBottom: '1.5rem',
    fontWeight: 600,
  },
  optionsList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.8rem',
  },
  optionBtn: {
    padding: '1rem 1.5rem',
    background: '#f8f9fa',
    border: '2px solid #e0e0e0',
    borderRadius: '10px',
    cursor: 'pointer',
    textAlign: 'left',
    fontSize: '1rem',
    color: '#333',
    display: 'flex',
    alignItems: 'center',
    gap: '1rem',
    transition: 'all 0.2s',
  },
  optionSelected: {
    padding: '1rem 1.5rem',
    background: '#e8f0fe',
    border: '2px solid #1a73e8',
    borderRadius: '10px',
    cursor: 'pointer',
    textAlign: 'left',
    fontSize: '1rem',
    color: '#1a73e8',
    fontWeight: 600,
    display: 'flex',
    alignItems: 'center',
    gap: '1rem',
  },
  optionLetter: {
    width: '30px',
    height: '30px',
    background: '#e0e0e0',
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontWeight: 700,
    flexShrink: 0,
  },
  examNav: {
    display: 'flex',
    justifyContent: 'space-between',
    gap: '1rem',
  },
  examNavBtn: {
    padding: '0.8rem 1.5rem',
    background: '#f0f0f0',
    border: 'none',
    borderRadius: '8px',
    cursor: 'pointer',
    fontSize: '1rem',
    color: '#333',
  },
  submitExamBtn: {
    padding: '0.8rem 1.5rem',
    background: 'linear-gradient(135deg, #28a745 0%, #1e7e34 100%)',
    border: 'none',
    borderRadius: '8px',
    cursor: 'pointer',
    fontSize: '1rem',
    color: 'white',
    fontWeight: 600,
  },
  
  // 考试结果
  examResult: {
    textAlign: 'center',
    maxWidth: '500px',
    margin: '0 auto',
  },
  resultPass: {
    background: 'linear-gradient(135deg, #d4edda 0%, #c3e6cb 100%)',
    borderRadius: '16px',
    padding: '3rem',
    marginBottom: '1.5rem',
  },
  resultFail: {
    background: 'linear-gradient(135deg, #f8d7da 0%, #f5c6cb 100%)',
    borderRadius: '16px',
    padding: '3rem',
    marginBottom: '1.5rem',
  },
  resultIcon: {
    fontSize: '4rem',
    marginBottom: '1rem',
  },
  resultScore: {
    fontSize: '2rem',
    fontWeight: 700,
    color: '#1a237e',
    marginBottom: '0.5rem',
  },
  resultDetail: {
    fontSize: '1.1rem',
    color: '#666',
  },
  retakeBtn: {
    padding: '1rem 2rem',
    background: 'linear-gradient(135deg, #1a73e8 0%, #0d47a1 100%)',
    border: 'none',
    borderRadius: '30px',
    color: 'white',
    fontSize: '1.1rem',
    fontWeight: 600,
    cursor: 'pointer',
  },
  
  // 证书
  certificateContainer: {
    maxWidth: '800px',
    margin: '0 auto',
    textAlign: 'center',
  },
  certificate: {
    background: 'white',
    borderRadius: '20px',
    padding: '2rem',
    marginBottom: '2rem',
    boxShadow: '0 8px 40px rgba(0,0,0,0.15)',
  },
  certificateBorder: {
    border: '4px solid #ffd700',
    borderRadius: '12px',
    padding: '2rem',
  },
  certificateContent: {
    textAlign: 'center',
  },
  certificateHeader: {
    marginBottom: '2rem',
  },
  certificateLogo: {
    fontSize: '5rem',
    marginBottom: '1rem',
  },
  certificateTitle: {
    fontSize: '2.5rem',
    color: '#1a237e',
    fontWeight: 700,
  },
  certificateBody: {
    marginBottom: '2rem',
  },
  certificateText: {
    fontSize: '1.2rem',
    color: '#666',
    marginBottom: '0.5rem',
  },
  certificateName: {
    fontSize: '2rem',
    color: '#1a237e',
    marginBottom: '1rem',
  },
  certificateCourse: {
    fontSize: '1.5rem',
    color: '#1a73e8',
    marginBottom: '1rem',
  },
  certificateSeal: {
    display: 'inline-block',
    background: 'linear-gradient(135deg, #28a745 0%, #1e7e34 100%)',
    color: 'white',
    padding: '0.8rem 2rem',
    borderRadius: '8px',
    fontSize: '1.2rem',
    fontWeight: 700,
    marginTop: '1rem',
  },
  certificateReward: {
    background: 'linear-gradient(135deg, #fff3cd 0%, #ffeeba 100%)',
    padding: '1rem',
    borderRadius: '8px',
    color: '#856404',
    fontSize: '1.1rem',
    fontWeight: 600,
  },
  
  // 流量说明
  speedNotice: {
    background: '#f8f9fa',
    borderRadius: '12px',
    padding: '1.2rem',
    marginTop: '1.5rem',
    borderLeft: '4px solid #1a73e8',
  },
  speedTitle: {
    fontSize: '1rem',
    fontWeight: 600,
    color: '#1a237e',
    marginBottom: '0.8rem',
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
  },
  speedContent: {
    fontSize: '0.9rem',
    color: '#666',
    lineHeight: 1.8,
  },
  highSpeedDot: {
    display: 'inline-block',
    width: '10px',
    height: '10px',
    background: '#28a745',
    borderRadius: '50%',
    marginRight: '0.5rem',
  },
  regularSpeedDot: {
    display: 'inline-block',
    width: '10px',
    height: '10px',
    background: '#ffc107',
    borderRadius: '50%',
    marginRight: '0.5rem',
  },
  speedTip: {
    marginTop: '0.8rem',
    color: '#1a73e8',
    fontWeight: 600,
  },
  
  // 个人中心菜单
  profileMenu: {
    display: 'flex',
    flexDirection: 'column',
    gap: '1rem',
    maxWidth: '800px',
    margin: '0 auto',
  },
  profileMenuItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '1rem',
    padding: '1.2rem',
    background: 'white',
    borderRadius: '12px',
    boxShadow: '0 2px 10px rgba(0,0,0,0.08)',
    cursor: 'pointer',
    transition: 'transform 0.2s, box-shadow 0.2s',
  },
  profileMenuIcon: {
    width: '50px',
    height: '50px',
    background: 'linear-gradient(135deg, #1a73e8 0%, #0d47a1 100%)',
    borderRadius: '12px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: 'white',
    fontSize: '1.3rem',
    flexShrink: 0,
  },
  profileMenuText: {
    flex: 1,
  },
  profileMenuTitle: {
    fontSize: '1.1rem',
    fontWeight: 600,
    color: '#1a237e',
    marginBottom: '0.3rem',
  },
  profileMenuDesc: {
    fontSize: '0.9rem',
    color: '#666',
  },
  profileMenuArrow: {
    color: '#ccc',
    fontSize: '1rem',
  },
  
  // 首页部门渗透率排行榜
  deptRankSection: {
    marginTop: '2rem',
    background: 'white',
    borderRadius: '16px',
    padding: '1.5rem',
    boxShadow: '0 4px 20px rgba(0,0,0,0.08)',
  },
  deptRankTitle: {
    fontSize: '1.2rem',
    color: '#1a237e',
    marginBottom: '1rem',
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
  },
  deptRankList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.8rem',
  },
  deptRankItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '1rem',
  },
  deptRankBadge: {
    width: '28px',
    height: '28px',
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#333',
    fontWeight: 700,
    fontSize: '0.85rem',
    flexShrink: 0,
  },
  deptRankName: {
    width: '120px',
    fontWeight: 600,
    color: '#333',
    fontSize: '0.95rem',
  },
  deptRankProgress: {
    flex: 1,
    display: 'flex',
    alignItems: 'center',
    gap: '0.8rem',
  },
  deptRankBar: {
    flex: 1,
    height: '12px',
    background: '#e0e0e0',
    borderRadius: '6px',
    overflow: 'hidden',
  },
  deptRankFill: {
    height: '100%',
    background: 'linear-gradient(90deg, #1a73e8, #0d47a1)',
    borderRadius: '6px',
  },
  deptRankValue: {
    fontWeight: 700,
    color: '#1a73e8',
    width: '50px',
    textAlign: 'right',
  },
  
  // 案例筛选
  casesFilter: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '1.5rem',
    gap: '1rem',
    flexWrap: 'wrap',
  },
  searchBox: {
    display: 'flex',
    alignItems: 'center',
    background: 'white',
    borderRadius: '30px',
    padding: '0.5rem 1rem',
    boxShadow: '0 2px 10px rgba(0,0,0,0.08)',
    flex: 1,
    maxWidth: '400px',
  },
  searchInput: {
    border: 'none',
    outline: 'none',
    marginLeft: '0.5rem',
    flex: 1,
    fontSize: '1rem',
  },
  filterGroup: {
    display: 'flex',
    gap: '0.8rem',
  },
  filterSelect: {
    padding: '0.6rem 1rem',
    border: '1px solid #e0e0e0',
    borderRadius: '8px',
    background: 'white',
    fontSize: '0.95rem',
    cursor: 'pointer',
  },
  
  // 案例卡片元信息
  caseMeta: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '0.5rem',
  },
  caseContributor: {
    fontSize: '0.85rem',
    color: '#666',
    display: 'flex',
    alignItems: 'center',
    gap: '0.3rem',
  },
  
  // 案例详情
  caseDetail: {
    maxWidth: '900px',
    margin: '0 auto',
  },
  caseDetailCard: {
    background: 'white',
    borderRadius: '20px',
    padding: '2rem',
    boxShadow: '0 4px 20px rgba(0,0,0,0.08)',
  },
  caseDetailHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '1rem',
  },
  caseDetailTitle: {
    fontSize: '1.8rem',
    color: '#1a237e',
    marginBottom: '1.5rem',
  },
  caseDetailStats: {
    display: 'flex',
    gap: '2rem',
    padding: '1.5rem',
    background: '#f8f9fa',
    borderRadius: '12px',
    marginBottom: '1.5rem',
  },
  caseDetailStat: {
    textAlign: 'center',
    flex: 1,
  },
  caseDetailStatNum: {
    fontSize: '1.8rem',
    fontWeight: 700,
    color: '#1a73e8',
  },
  caseDetailStatLabel: {
    fontSize: '0.9rem',
    color: '#666',
    marginTop: '0.3rem',
  },
  caseDetailDesc: {
    marginBottom: '1.5rem',
  },
  caseDetailDescTitle: {
    fontSize: '1.1rem',
    color: '#1a237e',
    marginBottom: '0.8rem',
  },
  caseDetailDescText: {
    color: '#666',
    lineHeight: 1.8,
  },
  caseDetailContent: {
    marginTop: '1.5rem',
  },
  caseDetailContentTitle: {
    fontSize: '1.1rem',
    color: '#1a237e',
    marginBottom: '0.8rem',
    marginTop: '1.5rem',
  },
  caseDetailContentText: {
    color: '#666',
    lineHeight: 1.8,
  },
  
  // 安装弹窗
  modalOverlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    background: 'rgba(0,0,0,0.5)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1000,
  },
  modalContent: {
    background: 'white',
    borderRadius: '20px',
    padding: '2rem',
    maxWidth: '500px',
    width: '90%',
    maxHeight: '80vh',
    overflow: 'auto',
    boxShadow: '0 10px 40px rgba(0,0,0,0.2)',
  },
  modalHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '1.5rem',
    paddingBottom: '1rem',
    borderBottom: '1px solid #e0e0e0',
  },
  modalHeaderTitle: {
    fontSize: '1.3rem',
    color: '#1a237e',
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
  },
  modalClose: {
    background: 'none',
    border: 'none',
    fontSize: '1.5rem',
    cursor: 'pointer',
    color: '#999',
  },
  modalBody: {
    display: 'flex',
    flexDirection: 'column',
    gap: '1.5rem',
  },
  installMethod: {
    padding: '1rem',
    background: '#f8f9fa',
    borderRadius: '12px',
  },
  installMethodTitle: {
    fontWeight: 600,
    color: '#1a237e',
    marginBottom: '0.8rem',
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
  },
  installMethodNum: {
    width: '24px',
    height: '24px',
    background: '#1a73e8',
    color: 'white',
    borderRadius: '50%',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '0.85rem',
  },
  installCmd: {
    background: '#2d2d2d',
    color: '#fff',
    padding: '0.8rem 1rem',
    borderRadius: '8px',
    fontFamily: 'monospace',
    fontSize: '0.9rem',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  copyBtn: {
    background: '#4a4a4a',
    border: 'none',
    color: 'white',
    padding: '0.3rem 0.8rem',
    borderRadius: '4px',
    cursor: 'pointer',
    fontSize: '0.8rem',
    display: 'flex',
    alignItems: 'center',
    gap: '0.3rem',
  },
  notSupportBadge: {
    background: '#ffc107',
    color: '#333',
    padding: '0.2rem 0.5rem',
    borderRadius: '4px',
    fontSize: '0.75rem',
    fontWeight: 600,
  },
  downloadInstallBtn: {
    width: '100%',
    padding: '0.8rem',
    background: 'linear-gradient(135deg, #1a73e8 0%, #0d47a1 100%)',
    border: 'none',
    borderRadius: '8px',
    color: 'white',
    fontSize: '1rem',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.5rem',
  },
  
  // 安装按钮
  installBtn: {
    padding: '0.5rem 1rem',
    background: 'linear-gradient(135deg, #28a745 0%, #1e7e34 100%)',
    border: 'none',
    borderRadius: '8px',
    color: 'white',
    cursor: 'pointer',
    fontSize: '0.9rem',
    display: 'flex',
    alignItems: 'center',
    gap: '0.3rem',
  },
  
  // 排行榜区域
  rankingsSection: {
    padding: '2rem',
    maxWidth: '1400px',
    margin: '0 auto',
  },
  rankingsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(500px, 1fr))',
    gap: '2rem',
  },
  rankingCard: {
    background: 'white',
    borderRadius: '16px',
    padding: '1.5rem',
    boxShadow: '0 4px 20px rgba(0,0,0,0.08)',
  },
  rankingTitle: {
    fontSize: '1.1rem',
    color: '#1a237e',
    marginBottom: '1rem',
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
  },
  rankingList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.6rem',
    maxHeight: '400px',
    overflowY: 'auto',
  },
  rankingItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.8rem',
    padding: '0.5rem',
    borderRadius: '8px',
  },
  rankingBadge: {
    width: '24px',
    height: '24px',
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#333',
    fontWeight: 700,
    fontSize: '0.8rem',
    flexShrink: 0,
  },
  rankingName: {
    width: '100px',
    fontWeight: 600,
    color: '#333',
    fontSize: '0.9rem',
    flexShrink: 0,
  },
  rankingProgress: {
    flex: 1,
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
  },
  rankingBar: {
    flex: 1,
    height: '10px',
    background: '#e0e0e0',
    borderRadius: '5px',
    overflow: 'hidden',
  },
  rankingFill: {
    height: '100%',
    background: 'linear-gradient(90deg, #1a73e8, #0d47a1)',
    borderRadius: '5px',
  },
  rankingValue: {
    fontWeight: 700,
    color: '#1a73e8',
    width: '45px',
    textAlign: 'right',
    fontSize: '0.9rem',
  },
  
  // 案例详情操作按钮
  caseDetailActions: {
    display: 'flex',
    gap: '1.5rem',
    padding: '1rem',
    background: '#f8f9fa',
    borderRadius: '12px',
    marginBottom: '1.5rem',
    alignItems: 'center',
  },
  likeBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    padding: '0.5rem 1rem',
    background: 'white',
    border: '1px solid #e0e0e0',
    borderRadius: '20px',
    cursor: 'pointer',
    color: '#666',
    fontSize: '0.9rem',
  },
  likeBtnActive: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    padding: '0.5rem 1rem',
    background: '#ffeaea',
    border: '1px solid #ff4d4f',
    borderRadius: '20px',
    cursor: 'pointer',
    color: '#ff4d4f',
    fontSize: '0.9rem',
  },
  ratingSection: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.3rem',
  },
  ratingLabel: {
    color: '#666',
    fontSize: '0.9rem',
  },
  star: {
    fontSize: '1.5rem',
    color: '#ddd',
    cursor: 'pointer',
  },
  starActive: {
    fontSize: '1.5rem',
    color: '#ffd700',
    cursor: 'pointer',
  },
  commentBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    padding: '0.5rem 1rem',
    background: 'white',
    border: '1px solid #e0e0e0',
    borderRadius: '20px',
    cursor: 'pointer',
    color: '#666',
    fontSize: '0.9rem',
  },
  commentInput: {
    display: 'flex',
    gap: '0.5rem',
    marginBottom: '1.5rem',
  },
  commentTextInput: {
    flex: 1,
    padding: '0.8rem 1rem',
    border: '1px solid #e0e0e0',
    borderRadius: '8px',
    fontSize: '0.95rem',
    outline: 'none',
  },
  commentSubmitBtn: {
    padding: '0.8rem 1.5rem',
    background: '#1a73e8',
    border: 'none',
    borderRadius: '8px',
    color: 'white',
    cursor: 'pointer',
    fontSize: '0.95rem',
  },
  commentList: {
    marginTop: '1rem',
    paddingTop: '1rem',
    borderTop: '1px solid #e0e0e0',
  },
  commentListTitle: {
    fontSize: '1rem',
    color: '#1a237e',
    marginBottom: '1rem',
  },
  commentItem: {
    padding: '0.8rem',
    background: '#f8f9fa',
    borderRadius: '8px',
    marginBottom: '0.8rem',
  },
  commentUser: {
    fontWeight: 600,
    color: '#1a237e',
    marginBottom: '0.3rem',
    fontSize: '0.9rem',
  },
  commentText: {
    color: '#666',
    fontSize: '0.95rem',
    marginBottom: '0.3rem',
  },
  commentTime: {
    fontSize: '0.8rem',
    color: '#999',
  },
  
  // 页面头部按钮组
  pageHeaderButtons: {
    display: 'flex',
    gap: '0.8rem',
  },
  
  // 技能需求区域
  requestsSection: {
    marginTop: '3rem',
    padding: '2rem',
    background: 'white',
    borderRadius: '16px',
    boxShadow: '0 4px 20px rgba(0,0,0,0.08)',
  },
  requestsTitle: {
    fontSize: '1.3rem',
    color: '#1a237e',
    marginBottom: '0.5rem',
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
  },
  requestsDesc: {
    color: '#666',
    marginBottom: '1.5rem',
  },
  requestsList: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(300px, 1fr))',
    gap: '1rem',
  },
  requestCard: {
    padding: '1.2rem',
    background: '#f8f9fa',
    borderRadius: '12px',
    border: '1px solid #e0e0e0',
  },
  requestHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '0.8rem',
  },
  requestCategory: {
    background: '#e8f0fe',
    color: '#1a73e8',
    padding: '0.2rem 0.6rem',
    borderRadius: '4px',
    fontSize: '0.8rem',
    fontWeight: 600,
  },
  voteBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.3rem',
    padding: '0.3rem 0.6rem',
    background: 'white',
    border: '1px solid #e0e0e0',
    borderRadius: '15px',
    cursor: 'pointer',
    fontSize: '0.8rem',
    color: '#666',
  },
  voteBtnActive: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.3rem',
    padding: '0.3rem 0.6rem',
    background: '#e8f5e9',
    border: '1px solid #4caf50',
    borderRadius: '15px',
    cursor: 'pointer',
    fontSize: '0.8rem',
    color: '#4caf50',
  },
  requestTitle: {
    fontSize: '1.1rem',
    color: '#1a237e',
    marginBottom: '0.5rem',
  },
  requestProblem: {
    color: '#666',
    fontSize: '0.95rem',
    lineHeight: 1.5,
    marginBottom: '0.8rem',
  },
  requestMeta: {
    display: 'flex',
    gap: '1rem',
    fontSize: '0.85rem',
    color: '#999',
  },
  // 首页部门渗透率排行榜
  deptPenetrationGrid: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '2rem',
  },
  deptPenetrationCard: {
    background: 'white',
    borderRadius: '12px',
    padding: '1.5rem',
    boxShadow: '0 2px 8px rgba(0,0,0,0.1)',
  },
  penetrationCardTitle: {
    fontSize: '1.1rem',
    color: '#333',
    marginBottom: '1rem',
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
  },
  penetrationList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.75rem',
  },
  penetrationItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '1rem',
  },
  penetrationRank: {
    width: '28px',
    height: '28px',
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#333',
    fontWeight: 'bold',
    fontSize: '0.85rem',
  },
  penetrationInfo: {
    flex: 1,
  },
  penetrationName: {
    fontSize: '0.9rem',
    color: '#333',
    marginBottom: '0.25rem',
  },
  penetrationBar: {
    height: '6px',
    background: '#e0e0e0',
    borderRadius: '3px',
    overflow: 'hidden',
  },
  penetrationFill: {
    height: '100%',
    background: 'linear-gradient(90deg, #1a73e8 0%, #0d47a1 100%)',
    borderRadius: '3px',
    transition: 'width 0.3s ease',
  },
  penetrationValue: {
    fontSize: '0.9rem',
    color: '#1a73e8',
    fontWeight: '600',
    minWidth: '45px',
    textAlign: 'right',
  },
  // 安全合规页样式
  learnSection: {
    maxWidth: '900px',
    margin: '0 auto',
  },
  learnCard: {
    background: 'white',
    borderRadius: '12px',
    padding: '1.5rem',
    marginBottom: '1rem',
    boxShadow: '0 2px 8px rgba(0,0,0,0.1)',
  },
  learnTitle: {
    color: '#1a237e',
    marginBottom: '1rem',
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
  },
  learnList: {
    paddingLeft: '1.5rem',
    lineHeight: 1.8,
    color: '#555',
  },
  examSection: {
    maxWidth: '800px',
    margin: '0 auto',
  },
  examInfo: {
    background: '#e3f2fd',
    padding: '1rem',
    borderRadius: '8px',
    marginBottom: '1.5rem',
    textAlign: 'center',
    color: '#1565c0',
  },
  examQuestion: {
    background: 'white',
    borderRadius: '12px',
    padding: '1.5rem',
    marginBottom: '1rem',
    boxShadow: '0 2px 8px rgba(0,0,0,0.1)',
  },
  questionText: {
    fontSize: '1rem',
    fontWeight: 600,
    marginBottom: '1rem',
    color: '#333',
  },
  optionsList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.75rem',
  },
  optionLabel: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.75rem',
    cursor: 'pointer',
    padding: '0.75rem',
    borderRadius: '8px',
    transition: 'background 0.2s',
  },
  optionText: {
    color: '#555',
  },
  optionTextSelected: {
    color: '#1a73e8',
    fontWeight: 600,
  },
  examResult: {
    textAlign: 'center',
    padding: '2rem',
  },
  passCard: {
    background: 'linear-gradient(135deg, #4caf50 0%, #2e7d32 100%)',
    color: 'white',
    borderRadius: '16px',
    padding: '2rem',
    marginBottom: '1.5rem',
  },
  failCard: {
    background: 'linear-gradient(135deg, #f44336 0%, #c62828 100%)',
    color: 'white',
    borderRadius: '16px',
    padding: '2rem',
    marginBottom: '1.5rem',
  },
  passIcon: {
    fontSize: '3rem',
    marginBottom: '1rem',
  },
  failIcon: {
    fontSize: '3rem',
    marginBottom: '1rem',
  },
  certificateCard: {
    background: 'linear-gradient(135deg, #ffd700 0%, #ffb300 100%)',
    borderRadius: '16px',
    padding: '3rem',
    maxWidth: '600px',
    margin: '2rem auto',
    textAlign: 'center',
    boxShadow: '0 8px 32px rgba(0,0,0,0.2)',
  },
  certificateIcon: {
    fontSize: '4rem',
    color: '#b71c1c',
    marginBottom: '1rem',
  },
  certificateTitle: {
    fontSize: '2rem',
    color: '#b71c1c',
    marginBottom: '1.5rem',
  },
  certificateBody: {
    background: 'white',
    borderRadius: '12px',
    padding: '2rem',
    marginBottom: '1.5rem',
  },
  certificateName: {
    fontSize: '2.5rem',
    color: '#1a237e',
    margin: '1rem 0',
  },
  certificateText: {
    fontSize: '1.1rem',
    color: '#555',
    margin: '0.5rem 0',
  },
  certificateSeal: {
    width: '80px',
    height: '80px',
    background: '#4caf50',
    color: 'white',
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '1.5rem',
    fontWeight: 'bold',
    margin: '1.5rem auto 0',
  },
  certificateFooter: {
    color: '#666',
    fontSize: '0.9rem',
  },
  // 案例详情页样式
  caseDetailCard: {
    background: 'white',
    borderRadius: '16px',
    padding: '2rem',
    marginTop: '1rem',
    boxShadow: '0 4px 16px rgba(0,0,0,0.1)',
  },
  caseDetailHeader: {
    marginBottom: '1.5rem',
  },
  caseDetailTitle: {
    fontSize: '1.8rem',
    color: '#1a237e',
    marginTop: '0.5rem',
  },
  caseDetailStats: {
    display: 'flex',
    gap: '2rem',
    marginBottom: '2rem',
    padding: '1rem',
    background: '#f5f5f5',
    borderRadius: '12px',
  },
  caseDetailContent: {
    marginBottom: '2rem',
  },
  detailSectionTitle: {
    fontSize: '1.2rem',
    color: '#333',
    marginBottom: '1rem',
    borderBottom: '2px solid #1a73e8',
    paddingBottom: '0.5rem',
  },
  caseDetailDesc: {
    lineHeight: 1.8,
    color: '#555',
    fontSize: '1rem',
  },
  caseDetailActions: {
    display: 'flex',
    alignItems: 'center',
    gap: '1.5rem',
    marginBottom: '2rem',
    padding: '1rem',
    background: '#f9f9f9',
    borderRadius: '8px',
  },
  likeBtn: {
    padding: '0.5rem 1rem',
    background: 'white',
    border: '2px solid #e0e0e0',
    borderRadius: '20px',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    color: '#666',
  },
  likedBtn: {
    padding: '0.5rem 1rem',
    background: '#ffebee',
    border: '2px solid #ef5350',
    borderRadius: '20px',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    color: '#ef5350',
  },
  ratingSection: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.25rem',
    color: '#ffc107',
  },
  starIcon: {
    fontSize: '1.2rem',
  },
  commentsSection: {
    marginTop: '1rem',
  },
  noComments: {
    color: '#999',
    textAlign: 'center',
    padding: '2rem',
  },
  commentsList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '1rem',
    marginBottom: '1rem',
  },
  commentItem: {
    display: 'flex',
    gap: '1rem',
    padding: '1rem',
    background: '#f9f9f9',
    borderRadius: '8px',
  },
  commentAvatar: {
    width: '40px',
    height: '40px',
    background: '#1a73e8',
    color: 'white',
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '0.85rem',
  },
  commentContent: {
    flex: 1,
  },
  commentText: {
    color: '#333',
    marginBottom: '0.25rem',
  },
  commentDate: {
    fontSize: '0.8rem',
    color: '#999',
  },
  commentForm: {
    marginTop: '1rem',
  },
  commentInput: {
    width: '100%',
    padding: '0.75rem',
    border: '2px solid #e0e0e0',
    borderRadius: '8px',
    fontSize: '1rem',
  },
  caseContributor: {
    fontSize: '0.85rem',
    color: '#666',
    marginLeft: '0.5rem',
  },
  // 流量说明
  flowNotice: {
    background: '#e3f2fd',
    padding: '0.75rem 1rem',
    borderRadius: '8px',
    marginBottom: '1.5rem',
    color: '#1565c0',
    fontSize: '0.9rem',
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
  },
  // 团队表格
  teamTable: {
    background: 'white',
    borderRadius: '12px',
    overflow: 'hidden',
    boxShadow: '0 2px 8px rgba(0,0,0,0.1)',
  },
  teamHeader: {
    display: 'grid',
    gridTemplateColumns: '1fr 1.5fr 1fr 1fr 1fr',
    background: '#f5f5f5',
    padding: '1rem',
    fontWeight: 600,
    color: '#333',
  },
  teamRow: {
    display: 'grid',
    gridTemplateColumns: '1fr 1.5fr 1fr 1fr 1fr',
    padding: '1rem',
    borderBottom: '1px solid #eee',
    alignItems: 'center',
  },
  teamCell: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    color: '#555',
  },
  teamAvatar: {
    width: '32px',
    height: '32px',
    background: '#1a73e8',
    color: 'white',
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '0.85rem',
  },
  noDataText: {
    textAlign: 'center',
    color: '#999',
    padding: '2rem',
  },
  approvalNotice: {
    background: '#fff3e0',
    padding: '0.75rem',
    borderRadius: '8px',
    marginBottom: '1rem',
    color: '#e65100',
    fontSize: '0.9rem',
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
  },
  // 安装弹窗样式
  installMethod: {
    marginBottom: '1.5rem',
    padding: '1rem',
    background: '#f9f9f9',
    borderRadius: '8px',
  },
  installMethodTitle: {
    fontSize: '1rem',
    color: '#333',
    marginBottom: '0.75rem',
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
  },
  commandBox: {
    background: '#263238',
    color: '#aed581',
    padding: '0.75rem 1rem',
    borderRadius: '6px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    fontFamily: 'monospace',
  },
  commandText: {
    fontSize: '0.9rem',
  },
  copyBtn: {
    background: '#4caf50',
    color: 'white',
    border: 'none',
    padding: '0.4rem 0.8rem',
    borderRadius: '4px',
    cursor: 'pointer',
    fontSize: '0.85rem',
  },
  installHint: {
    color: '#999',
    fontSize: '0.9rem',
    fontStyle: 'italic',
  },
  
  // 消息通知弹框样式
  modalOverlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    display: 'flex',
    justifyContent: 'flex-end',
    alignItems: 'flex-start',
    paddingTop: '80px',
    paddingRight: '20px',
    zIndex: 1000,
  },
  notificationModal: {
    background: 'white',
    borderRadius: '12px',
    width: '420px',
    maxHeight: '70vh',
    overflow: 'hidden',
    boxShadow: '0 10px 40px rgba(0, 0, 0, 0.2)',
    animation: 'slideIn 0.3s ease',
  },
  notificationHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '1rem 1.25rem',
    background: 'linear-gradient(135deg, #1a237e 0%, #0d47a1 100%)',
    color: 'white',
  },
  notificationTitle: {
    fontSize: '1.1rem',
    fontWeight: 600,
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
  },
  notificationClose: {
    background: 'rgba(255, 255, 255, 0.2)',
    border: 'none',
    color: 'white',
    width: '32px',
    height: '32px',
    borderRadius: '50%',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '1rem',
  },
  notificationTabs: {
    display: 'flex',
    borderBottom: '1px solid #e0e0e0',
    background: '#fafafa',
  },
  notificationTab: {
    flex: 1,
    padding: '0.75rem',
    background: 'transparent',
    border: 'none',
    cursor: 'pointer',
    fontSize: '0.85rem',
    color: '#666',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.4rem',
    position: 'relative',
    transition: 'all 0.2s',
  },
  notificationTabActive: {
    flex: 1,
    padding: '0.75rem',
    background: 'white',
    border: 'none',
    cursor: 'pointer',
    fontSize: '0.85rem',
    color: '#1a237e',
    fontWeight: 600,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.4rem',
    borderBottom: '2px solid #1a237e',
    position: 'relative',
  },
  notificationDot: {
    width: '8px',
    height: '8px',
    background: '#ff6b6b',
    borderRadius: '50%',
    marginLeft: '4px',
  },
  notificationBadgeSmall: {
    background: '#ff6b6b',
    color: 'white',
    borderRadius: '10px',
    padding: '0 6px',
    fontSize: '0.7rem',
    marginLeft: '4px',
  },
  notificationContent: {
    padding: '1rem',
    maxHeight: 'calc(70vh - 140px)',
    overflowY: 'auto',
  },
  notificationList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.75rem',
  },
  notificationItem: {
    padding: '0.875rem',
    background: '#f8f9fa',
    borderRadius: '8px',
    borderLeft: '3px solid #4ecdc4',
  },
  notificationItemHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '0.5rem',
  },
  notificationItemTitle: {
    fontSize: '0.95rem',
    fontWeight: 600,
    color: '#333',
    display: 'flex',
    alignItems: 'center',
    gap: '0.4rem',
  },
  notificationItemDate: {
    fontSize: '0.8rem',
    color: '#999',
  },
  notificationItemContent: {
    fontSize: '0.85rem',
    color: '#666',
    margin: 0,
    lineHeight: 1.5,
  },
  importantTag: {
    background: '#ff6b6b',
    color: 'white',
    padding: '0.15rem 0.4rem',
    borderRadius: '4px',
    fontSize: '0.7rem',
    marginRight: '0.4rem',
  },
  unreadDot: {
    width: '8px',
    height: '8px',
    background: '#4ecdc4',
    borderRadius: '50%',
    marginRight: '0.4rem',
    display: 'inline-block',
  },
};

export default styles;
